// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/setthasit/Lore/internal/connectors/gitrepo (interfaces: GitRepo)
//
// Generated by this command:
//
//	mockgen -destination gitrepo/gitrepo.go -package mock_gitrepo github.com/setthasit/Lore/internal/connectors/gitrepo GitRepo
//

// Package mock_gitrepo is a generated GoMock package.
package mock_gitrepo

import (
	context "context"
	reflect "reflect"

	gitrepo "github.com/setthasit/Lore/internal/connectors/gitrepo"
	gomock "go.uber.org/mock/gomock"
)

// MockGitRepo is a mock of GitRepo interface.
type MockGitRepo struct {
	ctrl     *gomock.Controller
	recorder *MockGitRepoMockRecorder
	isgomock struct{}
}

// MockGitRepoMockRecorder is the mock recorder for MockGitRepo.
type MockGitRepoMockRecorder struct {
	mock *MockGitRepo
}

// NewMockGitRepo creates a new mock instance.
func NewMockGitRepo(ctrl *gomock.Controller) *MockGitRepo {
	mock := &MockGitRepo{ctrl: ctrl}
	mock.recorder = &MockGitRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGitRepo) EXPECT() *MockGitRepoMockRecorder {
	return m.recorder
}

// Blame mocks base method.
func (m *MockGitRepo) Blame(ctx context.Context, path string, startLine, endLine int) ([]gitrepo.BlameSpan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Blame", ctx, path, startLine, endLine)
	ret0, _ := ret[0].([]gitrepo.BlameSpan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Blame indicates an expected call of Blame.
func (mr *MockGitRepoMockRecorder) Blame(ctx, path, startLine, endLine any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Blame", reflect.TypeOf((*MockGitRepo)(nil).Blame), ctx, path, startLine, endLine)
}

// HasFileAtHEAD mocks base method.
func (m *MockGitRepo) HasFileAtHEAD(ctx context.Context, path string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasFileAtHEAD", ctx, path)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasFileAtHEAD indicates an expected call of HasFileAtHEAD.
func (mr *MockGitRepoMockRecorder) HasFileAtHEAD(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasFileAtHEAD", reflect.TypeOf((*MockGitRepo)(nil).HasFileAtHEAD), ctx, path)
}

// Log mocks base method.
func (m *MockGitRepo) Log(ctx context.Context, path string) ([]gitrepo.CommitRef, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Log", ctx, path)
	ret0, _ := ret[0].([]gitrepo.CommitRef)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Log indicates an expected call of Log.
func (mr *MockGitRepoMockRecorder) Log(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Log", reflect.TypeOf((*MockGitRepo)(nil).Log), ctx, path)
}
