package plugbuild

import (
	"cmp"
	"fmt"
	"go/format"
	"slices"
	"strings"

	"github.com/setthasit/Lore/internal/errors/internalerror"
)

// engineModule is the module a custom binary is built out of: the engine plus
// somebody else's plugins, which is the only thing a custom binary ever is.
const engineModule = "github.com/setthasit/Lore"

// generatedFile is the composition root's name inside the scratch module. It
// matches cmd/lore/main.go so a build failure quotes a familiar file name.
const generatedFile = "main.go"

// The first line is the machine-readable form tooling greps for; the doc
// comment says where the file came from and why editing it is pointless,
// because a compile error will quote it and its reader will want both.
const generatedHeader = `// Code generated by lore build; DO NOT EDIT.

// Command lore is a generated composition root: the official plugin set plus
// the plugins named by ` + "`lore build --with`" + `. It is written into a temporary
// module that lore build deletes when the build finishes, so run lore build
// again rather than editing it.
package main

`

// Render generates the composition root for a set of coordinates. The plugins
// are emitted in module order rather than command-line order so that two builds
// of the same set produce the same source, and therefore the same registration
// order in the binary they compile.
func Render(coords []Coordinate) ([]byte, error) {
	sorted := sortedByModule(coords)
	if err := checkSet(sorted); err != nil {
		return nil, err
	}

	var src strings.Builder
	src.WriteString(generatedHeader)

	src.WriteString("import (\n\t\"os\"\n\n")
	fmt.Fprintf(&src, "\t%q\n\t%q\n", engineModule+"/app", engineModule+"/plugins")
	if len(sorted) > 0 {
		src.WriteString("\n")
	}
	for _, c := range sorted {
		// The alias is written even when it equals the package's own name: the
		// generator knows the name it was given, never the name the module
		// declares, and an alias makes the two agree by construction.
		fmt.Fprintf(&src, "\t%s %q\n", c.Package, c.Module)
	}
	src.WriteString(")\n\n")

	src.WriteString("func main() {\n\tos.Exit(app.Run(app.With(append(\n\t\tplugins.Official(),\n")
	for _, c := range sorted {
		fmt.Fprintf(&src, "\t\t%s.Plugin(),\n", c.Package)
	}
	src.WriteString("\t)...)))\n}\n")

	// A malformed template must fail here rather than emit source the go
	// command rejects with a diagnostic about generated code.
	formatted, err := format.Source([]byte(src.String()))
	if err != nil {
		return nil, internalerror.NewInternalError(
			"lore build generated a composition root that is not valid Go — this is a bug in lore, not in the plugins named", err)
	}
	return formatted, nil
}

// sortedByModule is the canonical order of a coordinate set: the generated
// source, the fetch sequence and the report all use it, so a build reads the
// same however the flags were ordered.
func sortedByModule(coords []Coordinate) []Coordinate {
	sorted := slices.Clone(coords)
	slices.SortFunc(sorted, func(a, b Coordinate) int { return cmp.Compare(a.Module, b.Module) })
	return sorted
}

// checkSet rejects a set that cannot be generated: the same module twice would
// register its plugins twice, and two modules sharing a package name would
// collide as import aliases.
func checkSet(coords []Coordinate) error {
	modules, packages := make(map[string]string, len(coords)), make(map[string]string, len(coords))
	for _, c := range coords {
		if seen, ok := modules[c.Module]; ok {
			return internalerror.NewBadRequestError(
				"--with names "+c.Module+" twice, at "+seen+" and "+c.Version+" — one build compiles in one version", nil)
		}
		if seen, ok := packages[c.Package]; ok {
			return internalerror.NewBadRequestError(
				"--with "+c.String()+" and "+seen+" both want the package name "+c.Package+
					" — give one of them an explicit =<package>", nil)
		}
		modules[c.Module], packages[c.Package] = c.Version, c.String()
	}
	return nil
}
