package plugbuild

import (
	"cmp"
	"fmt"
	"go/format"
	"slices"
	"strconv"
	"strings"

	"github.com/setthasit/Lore/internal/errors/internalerror"
)

const engineModule = "github.com/setthasit/Lore"

const generatedFile = "main.go"

const generatedHeader = `// Code generated by lore build; DO NOT EDIT.

package main

`

// Render emits the plugins in the given order; identical output needs identically ordered input.
func Render(coords []Coordinate) ([]byte, error) {
	if err := checkSet(coords); err != nil {
		return nil, err
	}

	var src strings.Builder
	src.WriteString(generatedHeader)

	src.WriteString("import (\n\t\"os\"\n\n")
	fmt.Fprintf(&src, "\t%q\n\t%q\n\n", engineModule+"/app", engineModule+"/plugins")
	for _, c := range coords {
		// The generator knows the name it was given, never the name the module declares.
		fmt.Fprintf(&src, "\t%s %q\n", c.Package, c.Module)
	}
	src.WriteString(")\n\n")

	src.WriteString("func main() {\n\tos.Exit(app.Run(append(\n\t\tplugins.Official(),\n")
	for _, c := range coords {
		fmt.Fprintf(&src, "\t\t%s.Plugin(),\n", c.Package)
	}
	src.WriteString("\t)...))\n}\n")

	formatted, err := format.Source([]byte(src.String()))
	if err != nil {
		return nil, internalerror.NewInternalError(
			"lore build generated a composition root that is not valid Go — this is a bug in lore, not in the plugins named", err)
	}
	return formatted, nil
}

func sortedByModule(coords []Coordinate) []Coordinate {
	sorted := slices.Clone(coords)
	slices.SortFunc(sorted, func(a, b Coordinate) int { return cmp.Compare(a.Module, b.Module) })
	return sorted
}

func checkSet(coords []Coordinate) error {
	modules, packages := make(map[string]string, len(coords)), make(map[string]string, len(coords))
	for _, c := range coords {
		if !isPackageName(c.Package) || reservedPackages[c.Package] || c.Package == "_" {
			return internalerror.NewBadRequestError(
				"--with "+c.String()+" wants the package name "+strconv.Quote(c.Package)+
					", which the generated composition root cannot import — pick another with =<package>", nil)
		}
		if seen, ok := modules[c.Module]; ok {
			return internalerror.NewBadRequestError(
				"--with names "+c.Module+" twice, at "+seen+" and "+c.Version+" — one build compiles in one version", nil)
		}
		if seen, ok := packages[c.Package]; ok {
			return internalerror.NewBadRequestError(
				"--with "+c.String()+" and "+seen+" both want the package name "+c.Package+
					" — give one of them an explicit =<package>", nil)
		}
		modules[c.Module], packages[c.Package] = c.Version, c.String()
	}
	return nil
}
