package plugbuild

import (
	"testing"

	"github.com/setthasit/Lore/internal/errors/internalerror"
)

// goldenRoot is asserted verbatim: a silent change to it changes what a custom binary registers.
const goldenRoot = `// Code generated by lore build; DO NOT EDIT.

package main

import (
	"os"

	"github.com/setthasit/Lore/app"
	"github.com/setthasit/Lore/plugins"

	acmecrm "github.com/acme/lore-crm/v2"
	linear "github.com/jdoe/lore-linear"
)

func main() {
	os.Exit(app.Run(append(
		plugins.Official(),
		acmecrm.Plugin(),
		linear.Plugin(),
	)...))
}
`

func TestRenderProducesTheGoldenCompositionRoot(t *testing.T) {
	coords := parseAll(t, "github.com/acme/lore-crm/v2@v2.0.1=acmecrm", "github.com/jdoe/lore-linear@v0.3.1")

	source, err := Render(coords)
	if err != nil {
		t.Fatalf("Render() = %v", err)
	}
	if got := string(source); got != goldenRoot {
		t.Errorf("Render() =\n%s\nwant\n%s", got, goldenRoot)
	}
}

func TestRenderRejectsCollidingSets(t *testing.T) {
	cases := map[string][]Coordinate{
		"the same module twice": {
			{Module: "github.com/jdoe/lore-linear", Version: "v0.3.1", Package: "linear"},
			{Module: "github.com/jdoe/lore-linear", Version: "v0.4.0", Package: "linear"},
		},
		"two modules with one package name": {
			{Module: "github.com/jdoe/lore-linear", Version: "v0.3.1", Package: "linear"},
			{Module: "gitlab.com/other/lore-linear", Version: "v1.0.0", Package: "linear"},
		},
	}

	for name, coords := range cases {
		if _, err := Render(coords); err == nil {
			t.Errorf("%s: Render() generated source that cannot compile", name)
		} else if !internalerror.IsBadRequest(err) {
			t.Errorf("%s: kind = %v, want bad request", name, internalerror.KindOf(err))
		}
	}
}

func TestRenderRejectsAPackageNameItCannotEmit(t *testing.T) {
	cases := map[string]string{
		"not an identifier":              "lore-linear",
		"a keyword":                      "func",
		"empty":                          "",
		"an import the root already has": "os",
		"package main":                   "main",
		"a builtin the root calls":       "append",
		"the blank identifier":           "_",
	}

	for name, pkg := range cases {
		coords := []Coordinate{{Module: "github.com/jdoe/lore-linear", Version: "v0.3.1", Package: pkg}}
		if _, err := Render(coords); err == nil {
			t.Errorf("%s: Render() generated source that cannot compile", name)
		} else if !internalerror.IsBadRequest(err) {
			t.Errorf("%s: kind = %v, want bad request", name, internalerror.KindOf(err))
		}
	}
}

func parseAll(t *testing.T, raws ...string) []Coordinate {
	t.Helper()

	coords := make([]Coordinate, 0, len(raws))
	for _, raw := range raws {
		c, err := ParseCoordinate(raw)
		if err != nil {
			t.Fatalf("ParseCoordinate(%q) = %v", raw, err)
		}
		coords = append(coords, c)
	}
	return coords
}
