package plugbuild

import (
	"go/parser"
	"go/token"
	"strings"
	"testing"

	"github.com/setthasit/Lore/internal/errors/internalerror"
)

// goldenRoot is the whole point of the package: a composition root that is
// cmd/lore/main.go with more arguments to app.With. It is asserted verbatim
// because every character of it is a compile-time contract with the engine, and
// a silent change to it is a change to what a custom binary registers.
const goldenRoot = `// Code generated by lore build; DO NOT EDIT.

// Command lore is a generated composition root: the official plugin set plus
// the plugins named by ` + "`lore build --with`" + `. It is written into a temporary
// module that lore build deletes when the build finishes, so run lore build
// again rather than editing it.
package main

import (
	"os"

	"github.com/setthasit/Lore/app"
	"github.com/setthasit/Lore/plugins"

	acmecrm "github.com/acme/lore-crm/v2"
	linear "github.com/jdoe/lore-linear"
)

func main() {
	os.Exit(app.Run(app.With(append(
		plugins.Official(),
		acmecrm.Plugin(),
		linear.Plugin(),
	)...)))
}
`

func TestRenderProducesTheGoldenCompositionRoot(t *testing.T) {
	// The flags are deliberately given out of order: two builds of one set must
	// generate one file, so the plugin order cannot come from the command line.
	coords := parseAll(t, "github.com/jdoe/lore-linear@v0.3.1", "github.com/acme/lore-crm/v2@v2.0.1=acmecrm")

	source, err := Render(coords)
	if err != nil {
		t.Fatalf("Render() = %v", err)
	}
	if got := string(source); got != goldenRoot {
		t.Errorf("Render() =\n%s\nwant\n%s", got, goldenRoot)
	}
}

func TestRenderProducesParseableGo(t *testing.T) {
	sets := map[string][]Coordinate{
		"official set alone": nil,
		"one plugin":         parseAll(t, "github.com/jdoe/lore-linear@v0.3.1"),
		"three plugins": parseAll(t,
			"github.com/jdoe/lore-linear@v0.3.1",
			"github.com/acme/lore-crm/v2@v2.0.1=acmecrm",
			"gitlab.com/team/lore-wiki@v1.2.0"),
	}

	for name, coords := range sets {
		source, err := Render(coords)
		if err != nil {
			t.Errorf("%s: Render() = %v", name, err)
			continue
		}
		file, err := parser.ParseFile(token.NewFileSet(), generatedFile, source, parser.SkipObjectResolution)
		if err != nil {
			t.Errorf("%s: generated source is not valid Go: %v\n%s", name, err, source)
			continue
		}
		if file.Name.Name != "main" {
			t.Errorf("%s: generated package = %q, want main", name, file.Name.Name)
		}
	}
}

// The generated file must say it is generated: it is the file a compile error
// quotes, and its reader has to know not to fix it in place.
func TestRenderMarksTheFileGenerated(t *testing.T) {
	source, err := Render(parseAll(t, "github.com/jdoe/lore-linear@v0.3.1"))
	if err != nil {
		t.Fatalf("Render() = %v", err)
	}
	if !strings.HasPrefix(string(source), "// Code generated by lore build; DO NOT EDIT.\n") {
		t.Errorf("generated source starts with %q, want the generated-code marker", firstLine(string(source)))
	}
}

func TestRenderRejectsCollidingSets(t *testing.T) {
	cases := map[string][]Coordinate{
		"the same module twice": {
			{Module: "github.com/jdoe/lore-linear", Version: "v0.3.1", Package: "linear"},
			{Module: "github.com/jdoe/lore-linear", Version: "v0.4.0", Package: "linear"},
		},
		"two modules with one package name": {
			{Module: "github.com/jdoe/lore-linear", Version: "v0.3.1", Package: "linear"},
			{Module: "gitlab.com/other/lore-linear", Version: "v1.0.0", Package: "linear"},
		},
	}

	for name, coords := range cases {
		if _, err := Render(coords); err == nil {
			t.Errorf("%s: Render() generated source that cannot compile", name)
		} else if internalerror.KindOf(err) != internalerror.KindBadRequest {
			t.Errorf("%s: kind = %v, want bad request", name, internalerror.KindOf(err))
		}
	}
}

func parseAll(t *testing.T, raws ...string) []Coordinate {
	t.Helper()

	coords := make([]Coordinate, 0, len(raws))
	for _, raw := range raws {
		c, err := ParseCoordinate(raw)
		if err != nil {
			t.Fatalf("ParseCoordinate(%q) = %v", raw, err)
		}
		coords = append(coords, c)
	}
	return coords
}

func firstLine(text string) string {
	line, _, _ := strings.Cut(text, "\n")
	return line
}
