// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/setthasit/Lore/sdk (interfaces: CodeRepo)
//
// Generated by this command:
//
//	mockgen -destination lore/coderepo.go -package mock_lore github.com/setthasit/Lore/sdk CodeRepo
//

// Package mock_lore is a generated GoMock package.
package mock_lore

import (
	context "context"
	reflect "reflect"

	lore "github.com/setthasit/Lore/sdk"
	gomock "go.uber.org/mock/gomock"
)

// MockCodeRepo is a mock of CodeRepo interface.
type MockCodeRepo struct {
	ctrl     *gomock.Controller
	recorder *MockCodeRepoMockRecorder
	isgomock struct{}
}

// MockCodeRepoMockRecorder is the mock recorder for MockCodeRepo.
type MockCodeRepoMockRecorder struct {
	mock *MockCodeRepo
}

// NewMockCodeRepo creates a new mock instance.
func NewMockCodeRepo(ctrl *gomock.Controller) *MockCodeRepo {
	mock := &MockCodeRepo{ctrl: ctrl}
	mock.recorder = &MockCodeRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCodeRepo) EXPECT() *MockCodeRepoMockRecorder {
	return m.recorder
}

// Blame mocks base method.
func (m *MockCodeRepo) Blame(ctx context.Context, path string, startLine, endLine int) ([]lore.BlameSpan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Blame", ctx, path, startLine, endLine)
	ret0, _ := ret[0].([]lore.BlameSpan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Blame indicates an expected call of Blame.
func (mr *MockCodeRepoMockRecorder) Blame(ctx, path, startLine, endLine any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Blame", reflect.TypeOf((*MockCodeRepo)(nil).Blame), ctx, path, startLine, endLine)
}

// HasFileAtHEAD mocks base method.
func (m *MockCodeRepo) HasFileAtHEAD(ctx context.Context, path string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasFileAtHEAD", ctx, path)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasFileAtHEAD indicates an expected call of HasFileAtHEAD.
func (mr *MockCodeRepoMockRecorder) HasFileAtHEAD(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasFileAtHEAD", reflect.TypeOf((*MockCodeRepo)(nil).HasFileAtHEAD), ctx, path)
}

// Log mocks base method.
func (m *MockCodeRepo) Log(ctx context.Context, path string) ([]lore.CommitRef, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Log", ctx, path)
	ret0, _ := ret[0].([]lore.CommitRef)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Log indicates an expected call of Log.
func (mr *MockCodeRepoMockRecorder) Log(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Log", reflect.TypeOf((*MockCodeRepo)(nil).Log), ctx, path)
}
