// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/setthasit/Lore/sdk (interfaces: Completer)
//
// Generated by this command:
//
//	mockgen -destination lore/completer.go -package mock_lore github.com/setthasit/Lore/sdk Completer
//

// Package mock_lore is a generated GoMock package.
package mock_lore

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCompleter is a mock of Completer interface.
type MockCompleter struct {
	ctrl     *gomock.Controller
	recorder *MockCompleterMockRecorder
	isgomock struct{}
}

// MockCompleterMockRecorder is the mock recorder for MockCompleter.
type MockCompleterMockRecorder struct {
	mock *MockCompleter
}

// NewMockCompleter creates a new mock instance.
func NewMockCompleter(ctrl *gomock.Controller) *MockCompleter {
	mock := &MockCompleter{ctrl: ctrl}
	mock.recorder = &MockCompleterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCompleter) EXPECT() *MockCompleterMockRecorder {
	return m.recorder
}

// Complete mocks base method.
func (m *MockCompleter) Complete(ctx context.Context, system, user string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Complete", ctx, system, user)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Complete indicates an expected call of Complete.
func (mr *MockCompleterMockRecorder) Complete(ctx, system, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Complete", reflect.TypeOf((*MockCompleter)(nil).Complete), ctx, system, user)
}
