// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/setthasit/Lore/sdk (interfaces: Connector)
//
// Generated by this command:
//
//	mockgen -destination lore/connector.go -package mock_lore github.com/setthasit/Lore/sdk Connector
//

// Package mock_lore is a generated GoMock package.
package mock_lore

import (
	context "context"
	iter "iter"
	reflect "reflect"

	lore "github.com/setthasit/Lore/sdk"
	gomock "go.uber.org/mock/gomock"
)

// MockConnector is a mock of Connector interface.
type MockConnector struct {
	ctrl     *gomock.Controller
	recorder *MockConnectorMockRecorder
	isgomock struct{}
}

// MockConnectorMockRecorder is the mock recorder for MockConnector.
type MockConnectorMockRecorder struct {
	mock *MockConnector
}

// NewMockConnector creates a new mock instance.
func NewMockConnector(ctrl *gomock.Controller) *MockConnector {
	mock := &MockConnector{ctrl: ctrl}
	mock.recorder = &MockConnectorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConnector) EXPECT() *MockConnectorMockRecorder {
	return m.recorder
}

// Changes mocks base method.
func (m *MockConnector) Changes(ctx context.Context, cursor lore.Cursor) iter.Seq2[lore.Batch, error] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Changes", ctx, cursor)
	ret0, _ := ret[0].(iter.Seq2[lore.Batch, error])
	return ret0
}

// Changes indicates an expected call of Changes.
func (mr *MockConnectorMockRecorder) Changes(ctx, cursor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Changes", reflect.TypeOf((*MockConnector)(nil).Changes), ctx, cursor)
}

// Name mocks base method.
func (m *MockConnector) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockConnectorMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockConnector)(nil).Name))
}
