// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v6.33.1
// source: lore/v1/lore.proto

package lorev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// QueryServiceClient is the client API for QueryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QueryServiceClient interface {
	FindDecision(ctx context.Context, in *FindDecisionRequest, opts ...grpc.CallOption) (*FindDecisionResponse, error)
	Why(ctx context.Context, in *WhyRequest, opts ...grpc.CallOption) (*WhyResponse, error)
	Trace(ctx context.Context, in *TraceRequest, opts ...grpc.CallOption) (*TraceResponse, error)
	ImpactOf(ctx context.Context, in *ImpactOfRequest, opts ...grpc.CallOption) (*ImpactOfResponse, error)
	HistoryOf(ctx context.Context, in *HistoryOfRequest, opts ...grpc.CallOption) (*HistoryOfResponse, error)
}

type queryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewQueryServiceClient(cc grpc.ClientConnInterface) QueryServiceClient {
	return &queryServiceClient{cc}
}

func (c *queryServiceClient) FindDecision(ctx context.Context, in *FindDecisionRequest, opts ...grpc.CallOption) (*FindDecisionResponse, error) {
	out := new(FindDecisionResponse)
	err := c.cc.Invoke(ctx, "/lore.v1.QueryService/FindDecision", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryServiceClient) Why(ctx context.Context, in *WhyRequest, opts ...grpc.CallOption) (*WhyResponse, error) {
	out := new(WhyResponse)
	err := c.cc.Invoke(ctx, "/lore.v1.QueryService/Why", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryServiceClient) Trace(ctx context.Context, in *TraceRequest, opts ...grpc.CallOption) (*TraceResponse, error) {
	out := new(TraceResponse)
	err := c.cc.Invoke(ctx, "/lore.v1.QueryService/Trace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryServiceClient) ImpactOf(ctx context.Context, in *ImpactOfRequest, opts ...grpc.CallOption) (*ImpactOfResponse, error) {
	out := new(ImpactOfResponse)
	err := c.cc.Invoke(ctx, "/lore.v1.QueryService/ImpactOf", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryServiceClient) HistoryOf(ctx context.Context, in *HistoryOfRequest, opts ...grpc.CallOption) (*HistoryOfResponse, error) {
	out := new(HistoryOfResponse)
	err := c.cc.Invoke(ctx, "/lore.v1.QueryService/HistoryOf", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServiceServer is the server API for QueryService service.
// All implementations must embed UnimplementedQueryServiceServer
// for forward compatibility
type QueryServiceServer interface {
	FindDecision(context.Context, *FindDecisionRequest) (*FindDecisionResponse, error)
	Why(context.Context, *WhyRequest) (*WhyResponse, error)
	Trace(context.Context, *TraceRequest) (*TraceResponse, error)
	ImpactOf(context.Context, *ImpactOfRequest) (*ImpactOfResponse, error)
	HistoryOf(context.Context, *HistoryOfRequest) (*HistoryOfResponse, error)
	mustEmbedUnimplementedQueryServiceServer()
}

// UnimplementedQueryServiceServer must be embedded to have forward compatible implementations.
type UnimplementedQueryServiceServer struct {
}

func (UnimplementedQueryServiceServer) FindDecision(context.Context, *FindDecisionRequest) (*FindDecisionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindDecision not implemented")
}
func (UnimplementedQueryServiceServer) Why(context.Context, *WhyRequest) (*WhyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Why not implemented")
}
func (UnimplementedQueryServiceServer) Trace(context.Context, *TraceRequest) (*TraceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Trace not implemented")
}
func (UnimplementedQueryServiceServer) ImpactOf(context.Context, *ImpactOfRequest) (*ImpactOfResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ImpactOf not implemented")
}
func (UnimplementedQueryServiceServer) HistoryOf(context.Context, *HistoryOfRequest) (*HistoryOfResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HistoryOf not implemented")
}
func (UnimplementedQueryServiceServer) mustEmbedUnimplementedQueryServiceServer() {}

// UnsafeQueryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueryServiceServer will
// result in compilation errors.
type UnsafeQueryServiceServer interface {
	mustEmbedUnimplementedQueryServiceServer()
}

func RegisterQueryServiceServer(s grpc.ServiceRegistrar, srv QueryServiceServer) {
	s.RegisterService(&QueryService_ServiceDesc, srv)
}

func _QueryService_FindDecision_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindDecisionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServiceServer).FindDecision(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lore.v1.QueryService/FindDecision",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServiceServer).FindDecision(ctx, req.(*FindDecisionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueryService_Why_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WhyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServiceServer).Why(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lore.v1.QueryService/Why",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServiceServer).Why(ctx, req.(*WhyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueryService_Trace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TraceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServiceServer).Trace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lore.v1.QueryService/Trace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServiceServer).Trace(ctx, req.(*TraceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueryService_ImpactOf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImpactOfRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServiceServer).ImpactOf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lore.v1.QueryService/ImpactOf",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServiceServer).ImpactOf(ctx, req.(*ImpactOfRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueryService_HistoryOf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HistoryOfRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServiceServer).HistoryOf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lore.v1.QueryService/HistoryOf",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServiceServer).HistoryOf(ctx, req.(*HistoryOfRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// QueryService_ServiceDesc is the grpc.ServiceDesc for QueryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var QueryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lore.v1.QueryService",
	HandlerType: (*QueryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindDecision",
			Handler:    _QueryService_FindDecision_Handler,
		},
		{
			MethodName: "Why",
			Handler:    _QueryService_Why_Handler,
		},
		{
			MethodName: "Trace",
			Handler:    _QueryService_Trace_Handler,
		},
		{
			MethodName: "ImpactOf",
			Handler:    _QueryService_ImpactOf_Handler,
		},
		{
			MethodName: "HistoryOf",
			Handler:    _QueryService_HistoryOf_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lore/v1/lore.proto",
}

// SyncServiceClient is the client API for SyncService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SyncServiceClient interface {
	Trigger(ctx context.Context, in *TriggerRequest, opts ...grpc.CallOption) (*TriggerResponse, error)
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	Watch(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (SyncService_WatchClient, error)
}

type syncServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSyncServiceClient(cc grpc.ClientConnInterface) SyncServiceClient {
	return &syncServiceClient{cc}
}

func (c *syncServiceClient) Trigger(ctx context.Context, in *TriggerRequest, opts ...grpc.CallOption) (*TriggerResponse, error) {
	out := new(TriggerResponse)
	err := c.cc.Invoke(ctx, "/lore.v1.SyncService/Trigger", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncServiceClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, "/lore.v1.SyncService/Status", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncServiceClient) Watch(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (SyncService_WatchClient, error) {
	stream, err := c.cc.NewStream(ctx, &SyncService_ServiceDesc.Streams[0], "/lore.v1.SyncService/Watch", opts...)
	if err != nil {
		return nil, err
	}
	x := &syncServiceWatchClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SyncService_WatchClient interface {
	Recv() (*SyncEvent, error)
	grpc.ClientStream
}

type syncServiceWatchClient struct {
	grpc.ClientStream
}

func (x *syncServiceWatchClient) Recv() (*SyncEvent, error) {
	m := new(SyncEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SyncServiceServer is the server API for SyncService service.
// All implementations must embed UnimplementedSyncServiceServer
// for forward compatibility
type SyncServiceServer interface {
	Trigger(context.Context, *TriggerRequest) (*TriggerResponse, error)
	Status(context.Context, *StatusRequest) (*StatusResponse, error)
	Watch(*WatchRequest, SyncService_WatchServer) error
	mustEmbedUnimplementedSyncServiceServer()
}

// UnimplementedSyncServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSyncServiceServer struct {
}

func (UnimplementedSyncServiceServer) Trigger(context.Context, *TriggerRequest) (*TriggerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Trigger not implemented")
}
func (UnimplementedSyncServiceServer) Status(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedSyncServiceServer) Watch(*WatchRequest, SyncService_WatchServer) error {
	return status.Errorf(codes.Unimplemented, "method Watch not implemented")
}
func (UnimplementedSyncServiceServer) mustEmbedUnimplementedSyncServiceServer() {}

// UnsafeSyncServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SyncServiceServer will
// result in compilation errors.
type UnsafeSyncServiceServer interface {
	mustEmbedUnimplementedSyncServiceServer()
}

func RegisterSyncServiceServer(s grpc.ServiceRegistrar, srv SyncServiceServer) {
	s.RegisterService(&SyncService_ServiceDesc, srv)
}

func _SyncService_Trigger_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TriggerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncServiceServer).Trigger(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lore.v1.SyncService/Trigger",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncServiceServer).Trigger(ctx, req.(*TriggerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncService_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncServiceServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lore.v1.SyncService/Status",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncServiceServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncService_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SyncServiceServer).Watch(m, &syncServiceWatchServer{stream})
}

type SyncService_WatchServer interface {
	Send(*SyncEvent) error
	grpc.ServerStream
}

type syncServiceWatchServer struct {
	grpc.ServerStream
}

func (x *syncServiceWatchServer) Send(m *SyncEvent) error {
	return x.ServerStream.SendMsg(m)
}

// SyncService_ServiceDesc is the grpc.ServiceDesc for SyncService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SyncService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lore.v1.SyncService",
	HandlerType: (*SyncServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Trigger",
			Handler:    _SyncService_Trigger_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _SyncService_Status_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Watch",
			Handler:       _SyncService_Watch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "lore/v1/lore.proto",
}
