// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.33.1
// source: lore/v1/lore.proto

package lorev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AnchorKind int32

const (
	AnchorKind_ANCHOR_KIND_UNSPECIFIED AnchorKind = 0
	AnchorKind_ANCHOR_KIND_QUERY       AnchorKind = 1
	AnchorKind_ANCHOR_KIND_CODE_SPAN   AnchorKind = 2
	AnchorKind_ANCHOR_KIND_DOCUMENT    AnchorKind = 3
	AnchorKind_ANCHOR_KIND_TIME_WINDOW AnchorKind = 4
)

// Enum value maps for AnchorKind.
var (
	AnchorKind_name = map[int32]string{
		0: "ANCHOR_KIND_UNSPECIFIED",
		1: "ANCHOR_KIND_QUERY",
		2: "ANCHOR_KIND_CODE_SPAN",
		3: "ANCHOR_KIND_DOCUMENT",
		4: "ANCHOR_KIND_TIME_WINDOW",
	}
	AnchorKind_value = map[string]int32{
		"ANCHOR_KIND_UNSPECIFIED": 0,
		"ANCHOR_KIND_QUERY":       1,
		"ANCHOR_KIND_CODE_SPAN":   2,
		"ANCHOR_KIND_DOCUMENT":    3,
		"ANCHOR_KIND_TIME_WINDOW": 4,
	}
)

func (x AnchorKind) Enum() *AnchorKind {
	p := new(AnchorKind)
	*p = x
	return p
}

func (x AnchorKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AnchorKind) Descriptor() protoreflect.EnumDescriptor {
	return file_lore_v1_lore_proto_enumTypes[0].Descriptor()
}

func (AnchorKind) Type() protoreflect.EnumType {
	return &file_lore_v1_lore_proto_enumTypes[0]
}

func (x AnchorKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AnchorKind.Descriptor instead.
func (AnchorKind) EnumDescriptor() ([]byte, []int) {
	return file_lore_v1_lore_proto_rawDescGZIP(), []int{0}
}

type NodeRole int32

const (
	NodeRole_NODE_ROLE_UNSPECIFIED    NodeRole = 0
	NodeRole_NODE_ROLE_SEED           NodeRole = 1
	NodeRole_NODE_ROLE_BLAMED_COMMIT  NodeRole = 2
	NodeRole_NODE_ROLE_REVIEW_THREAD  NodeRole = 3
	NodeRole_NODE_ROLE_LINKED_TICKET  NodeRole = 4
	NodeRole_NODE_ROLE_DESIGN_DOC     NodeRole = 5
	NodeRole_NODE_ROLE_FOLLOW_UP      NodeRole = 6
	NodeRole_NODE_ROLE_SEMANTIC_MATCH NodeRole = 7
	NodeRole_NODE_ROLE_LINKED_CHANGE  NodeRole = 8
)

// Enum value maps for NodeRole.
var (
	NodeRole_name = map[int32]string{
		0: "NODE_ROLE_UNSPECIFIED",
		1: "NODE_ROLE_SEED",
		2: "NODE_ROLE_BLAMED_COMMIT",
		3: "NODE_ROLE_REVIEW_THREAD",
		4: "NODE_ROLE_LINKED_TICKET",
		5: "NODE_ROLE_DESIGN_DOC",
		6: "NODE_ROLE_FOLLOW_UP",
		7: "NODE_ROLE_SEMANTIC_MATCH",
		8: "NODE_ROLE_LINKED_CHANGE",
	}
	NodeRole_value = map[string]int32{
		"NODE_ROLE_UNSPECIFIED":    0,
		"NODE_ROLE_SEED":           1,
		"NODE_ROLE_BLAMED_COMMIT":  2,
		"NODE_ROLE_REVIEW_THREAD":  3,
		"NODE_ROLE_LINKED_TICKET":  4,
		"NODE_ROLE_DESIGN_DOC":     5,
		"NODE_ROLE_FOLLOW_UP":      6,
		"NODE_ROLE_SEMANTIC_MATCH": 7,
		"NODE_ROLE_LINKED_CHANGE":  8,
	}
)

func (x NodeRole) Enum() *NodeRole {
	p := new(NodeRole)
	*p = x
	return p
}

func (x NodeRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeRole) Descriptor() protoreflect.EnumDescriptor {
	return file_lore_v1_lore_proto_enumTypes[1].Descriptor()
}

func (NodeRole) Type() protoreflect.EnumType {
	return &file_lore_v1_lore_proto_enumTypes[1]
}

func (x NodeRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeRole.Descriptor instead.
func (NodeRole) EnumDescriptor() ([]byte, []int) {
	return file_lore_v1_lore_proto_rawDescGZIP(), []int{1}
}

type EdgeKind int32

const (
	EdgeKind_EDGE_KIND_UNSPECIFIED     EdgeKind = 0
	EdgeKind_EDGE_KIND_COMMIT_IN_PR    EdgeKind = 1
	EdgeKind_EDGE_KIND_PR_CLOSES_ISSUE EdgeKind = 2
	EdgeKind_EDGE_KIND_REFERENCES_DOC  EdgeKind = 3
	EdgeKind_EDGE_KIND_MENTIONS_COMMIT EdgeKind = 4
	EdgeKind_EDGE_KIND_MENTIONS_PATH   EdgeKind = 5
	EdgeKind_EDGE_KIND_SUPERSEDES      EdgeKind = 6
)

// Enum value maps for EdgeKind.
var (
	EdgeKind_name = map[int32]string{
		0: "EDGE_KIND_UNSPECIFIED",
		1: "EDGE_KIND_COMMIT_IN_PR",
		2: "EDGE_KIND_PR_CLOSES_ISSUE",
		3: "EDGE_KIND_REFERENCES_DOC",
		4: "EDGE_KIND_MENTIONS_COMMIT",
		5: "EDGE_KIND_MENTIONS_PATH",
		6: "EDGE_KIND_SUPERSEDES",
	}
	EdgeKind_value = map[string]int32{
		"EDGE_KIND_UNSPECIFIED":     0,
		"EDGE_KIND_COMMIT_IN_PR":    1,
		"EDGE_KIND_PR_CLOSES_ISSUE": 2,
		"EDGE_KIND_REFERENCES_DOC":  3,
		"EDGE_KIND_MENTIONS_COMMIT": 4,
		"EDGE_KIND_MENTIONS_PATH":   5,
		"EDGE_KIND_SUPERSEDES":      6,
	}
)

func (x EdgeKind) Enum() *EdgeKind {
	p := new(EdgeKind)
	*p = x
	return p
}

func (x EdgeKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EdgeKind) Descriptor() protoreflect.EnumDescriptor {
	return file_lore_v1_lore_proto_enumTypes[2].Descriptor()
}

func (EdgeKind) Type() protoreflect.EnumType {
	return &file_lore_v1_lore_proto_enumTypes[2]
}

func (x EdgeKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EdgeKind.Descriptor instead.
func (EdgeKind) EnumDescriptor() ([]byte, []int) {
	return file_lore_v1_lore_proto_rawDescGZIP(), []int{2}
}

type Direction int32

const (
	Direction_DIRECTION_UNSPECIFIED Direction = 0
	Direction_DIRECTION_OUT         Direction = 1
	Direction_DIRECTION_IN          Direction = 2
	Direction_DIRECTION_BOTH        Direction = 3
)

// Enum value maps for Direction.
var (
	Direction_name = map[int32]string{
		0: "DIRECTION_UNSPECIFIED",
		1: "DIRECTION_OUT",
		2: "DIRECTION_IN",
		3: "DIRECTION_BOTH",
	}
	Direction_value = map[string]int32{
		"DIRECTION_UNSPECIFIED": 0,
		"DIRECTION_OUT":         1,
		"DIRECTION_IN":          2,
		"DIRECTION_BOTH":        3,
	}
)

func (x Direction) Enum() *Direction {
	p := new(Direction)
	*p = x
	return p
}

func (x Direction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Direction) Descriptor() protoreflect.EnumDescriptor {
	return file_lore_v1_lore_proto_enumTypes[3].Descriptor()
}

func (Direction) Type() protoreflect.EnumType {
	return &file_lore_v1_lore_proto_enumTypes[3]
}

func (x Direction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Direction.Descriptor instead.
func (Direction) EnumDescriptor() ([]byte, []int) {
	return file_lore_v1_lore_proto_rawDescGZIP(), []int{3}
}

type SyncPhase int32

const (
	SyncPhase_SYNC_PHASE_UNSPECIFIED        SyncPhase = 0
	SyncPhase_SYNC_PHASE_ROUND_STARTED      SyncPhase = 1
	SyncPhase_SYNC_PHASE_BATCH_STORED       SyncPhase = 2
	SyncPhase_SYNC_PHASE_CHUNKS_INDEXED     SyncPhase = 3
	SyncPhase_SYNC_PHASE_CONNECTOR_FINISHED SyncPhase = 4
	SyncPhase_SYNC_PHASE_PENDING_LINKED     SyncPhase = 5
	SyncPhase_SYNC_PHASE_ROUND_FINISHED     SyncPhase = 6
	SyncPhase_SYNC_PHASE_FAILED             SyncPhase = 7
)

// Enum value maps for SyncPhase.
var (
	SyncPhase_name = map[int32]string{
		0: "SYNC_PHASE_UNSPECIFIED",
		1: "SYNC_PHASE_ROUND_STARTED",
		2: "SYNC_PHASE_BATCH_STORED",
		3: "SYNC_PHASE_CHUNKS_INDEXED",
		4: "SYNC_PHASE_CONNECTOR_FINISHED",
		5: "SYNC_PHASE_PENDING_LINKED",
		6: "SYNC_PHASE_ROUND_FINISHED",
		7: "SYNC_PHASE_FAILED",
	}
	SyncPhase_value = map[string]int32{
		"SYNC_PHASE_UNSPECIFIED":        0,
		"SYNC_PHASE_ROUND_STARTED":      1,
		"SYNC_PHASE_BATCH_STORED":       2,
		"SYNC_PHASE_CHUNKS_INDEXED":     3,
		"SYNC_PHASE_CONNECTOR_FINISHED": 4,
		"SYNC_PHASE_PENDING_LINKED":     5,
		"SYNC_PHASE_ROUND_FINISHED":     6,
		"SYNC_PHASE_FAILED":             7,
	}
)

func (x SyncPhase) Enum() *SyncPhase {
	p := new(SyncPhase)
	*p = x
	return p
}

func (x SyncPhase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SyncPhase) Descriptor() protoreflect.EnumDescriptor {
	return file_lore_v1_lore_proto_enumTypes[4].Descriptor()
}

func (SyncPhase) Type() protoreflect.EnumType {
	return &file_lore_v1_lore_proto_enumTypes[4]
}

func (x SyncPhase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SyncPhase.Descriptor instead.
func (SyncPhase) EnumDescriptor() ([]byte, []int) {
	return file_lore_v1_lore_proto_rawDescGZIP(), []int{4}
}

type FindDecisionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Question      string                 `protobuf:"bytes,1,opt,name=question,proto3" json:"question,omitempty"`
	Around        string                 `protobuf:"bytes,2,opt,name=around,proto3" json:"around,omitempty"`
	Source        string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	Repo          string                 `protobuf:"bytes,4,opt,name=repo,proto3" json:"repo,omitempty"`
	DocType       string                 `protobuf:"bytes,5,opt,name=doc_type,json=docType,proto3" json:"doc_type,omitempty"`
	Since         *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=since,proto3" json:"since,omitempty"`
	Until         *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=until,proto3" json:"until,omitempty"`
	Synthesize    *bool                  `protobuf:"varint,8,opt,name=synthesize,proto3,oneof" json:"synthesize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindDecisionRequest) Reset() {
	*x = FindDecisionRequest{}
	mi := &file_lore_v1_lore_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindDecisionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindDecisionRequest) ProtoMessage() {}

func (x *FindDecisionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lore_v1_lore_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindDecisionRequest.ProtoReflect.Descriptor instead.
func (*FindDecisionRequest) Descriptor() ([]byte, []int) {
	return file_lore_v1_lore_proto_rawDescGZIP(), []int{0}
}

func (x *FindDecisionRequest) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *FindDecisionRequest) GetAround() string {
	if x != nil {
		return x.Around
	}
	return ""
}

func (x *FindDecisionRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *FindDecisionRequest) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *FindDecisionRequest) GetDocType() string {
	if x != nil {
		return x.DocType
	}
	return ""
}

func (x *FindDecisionRequest) GetSince() *timestamppb.Timestamp {
	if x != nil {
		return x.Since
	}
	return nil
}

func (x *FindDecisionRequest) GetUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.Until
	}
	return nil
}

func (x *FindDecisionRequest) GetSynthesize() bool {
	if x != nil && x.Synthesize != nil {
		return *x.Synthesize
	}
	return false
}

type FindDecisionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bundle        *EvidenceBundle        `protobuf:"bytes,1,opt,name=bundle,proto3" json:"bundle,omitempty"`
	Synthesis     string                 `protobuf:"bytes,2,opt,name=synthesis,proto3" json:"synthesis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindDecisionResponse) Reset() {
	*x = FindDecisionResponse{}
	mi := &file_lore_v1_lore_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindDecisionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindDecisionResponse) ProtoMessage() {}

func (x *FindDecisionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lore_v1_lore_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindDecisionResponse.ProtoReflect.Descriptor instead.
func (*FindDecisionResponse) Descriptor() ([]byte, []int) {
	return file_lore_v1_lore_proto_rawDescGZIP(), []int{1}
}

func (x *FindDecisionResponse) GetBundle() *EvidenceBundle {
	if x != nil {
		return x.Bundle
	}
	return nil
}

func (x *FindDecisionResponse) GetSynthesis() string {
	if x != nil {
		return x.Synthesis
	}
	return ""
}

type WhyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repo          string                 `protobuf:"bytes,1,opt,name=repo,proto3" json:"repo,omitempty"`
	File          string                 `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty"`
	LineStart     int32                  `protobuf:"varint,3,opt,name=line_start,json=lineStart,proto3" json:"line_start,omitempty"`
	LineEnd       int32                  `protobuf:"varint,4,opt,name=line_end,json=lineEnd,proto3" json:"line_end,omitempty"`
	Question      string                 `protobuf:"bytes,5,opt,name=question,proto3" json:"question,omitempty"`
	Synthesize    *bool                  `protobuf:"varint,6,opt,name=synthesize,proto3,oneof" json:"synthesize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WhyRequest) Reset() {
	*x = WhyRequest{}
	mi := &file_lore_v1_lore_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WhyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhyRequest) ProtoMessage() {}

func (x *WhyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lore_v1_lore_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhyRequest.ProtoReflect.Descriptor instead.
func (*WhyRequest) Descriptor() ([]byte, []int) {
	return file_lore_v1_lore_proto_rawDescGZIP(), []int{2}
}

func (x *WhyRequest) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *WhyRequest) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *WhyRequest) GetLineStart() int32 {
	if x != nil {
		return x.LineStart
	}
	return 0
}

func (x *WhyRequest) GetLineEnd() int32 {
	if x != nil {
		return x.LineEnd
	}
	return 0
}

func (x *WhyRequest) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *WhyRequest) GetSynthesize() bool {
	if x != nil && x.Synthesize != nil {
		return *x.Synthesize
	}
	return false
}

type WhyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bundle        *EvidenceBundle        `protobuf:"bytes,1,opt,name=bundle,proto3" json:"bundle,omitempty"`
	Synthesis     string                 `protobuf:"bytes,2,opt,name=synthesis,proto3" json:"synthesis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WhyResponse) Reset() {
	*x = WhyResponse{}
	mi := &file_lore_v1_lore_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WhyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhyResponse) ProtoMessage() {}

func (x *WhyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lore_v1_lore_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhyResponse.ProtoReflect.Descriptor instead.
func (*WhyResponse) Descriptor() ([]byte, []int) {
	return file_lore_v1_lore_proto_rawDescGZIP(), []int{3}
}

func (x *WhyResponse) GetBundle() *EvidenceBundle {
	if x != nil {
		return x.Bundle
	}
	return nil
}

func (x *WhyResponse) GetSynthesis() string {
	if x != nil {
		return x.Synthesis
	}
	return ""
}

type TraceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ref           string                 `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	Direction     Direction              `protobuf:"varint,2,opt,name=direction,proto3,enum=lore.v1.Direction" json:"direction,omitempty"`
	Depth         int32                  `protobuf:"varint,3,opt,name=depth,proto3" json:"depth,omitempty"`
	Synthesize    *bool                  `protobuf:"varint,4,opt,name=synthesize,proto3,oneof" json:"synthesize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TraceRequest) Reset() {
	*x = TraceRequest{}
	mi := &file_lore_v1_lore_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TraceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TraceRequest) ProtoMessage() {}

func (x *TraceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lore_v1_lore_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TraceRequest.ProtoReflect.Descriptor instead.
func (*TraceRequest) Descriptor() ([]byte, []int) {
	return file_lore_v1_lore_proto_rawDescGZIP(), []int{4}
}

func (x *TraceRequest) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

func (x *TraceRequest) GetDirection() Direction {
	if x != nil {
		return x.Direction
	}
	return Direction_DIRECTION_UNSPECIFIED
}

func (x *TraceRequest) GetDepth() int32 {
	if x != nil {
		return x.Depth
	}
	return 0
}

func (x *TraceRequest) GetSynthesize() bool {
	if x != nil && x.Synthesize != nil {
		return *x.Synthesize
	}
	return false
}

type TraceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bundle        *EvidenceBundle        `protobuf:"bytes,1,opt,name=bundle,proto3" json:"bundle,omitempty"`
	Synthesis     string                 `protobuf:"bytes,2,opt,name=synthesis,proto3" json:"synthesis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TraceResponse) Reset() {
	*x = TraceResponse{}
	mi := &file_lore_v1_lore_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TraceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TraceResponse) ProtoMessage() {}

func (x *TraceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lore_v1_lore_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TraceResponse.ProtoReflect.Descriptor instead.
func (*TraceResponse) Descriptor() ([]byte, []int) {
	return file_lore_v1_lore_proto_rawDescGZIP(), []int{5}
}

func (x *TraceResponse) GetBundle() *EvidenceBundle {
	if x != nil {
		return x.Bundle
	}
	return nil
}

func (x *TraceResponse) GetSynthesis() string {
	if x != nil {
		return x.Synthesis
	}
	return ""
}

type ImpactOfRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefOrQuery    string                 `protobuf:"bytes,1,opt,name=ref_or_query,json=refOrQuery,proto3" json:"ref_or_query,omitempty"`
	Question      string                 `protobuf:"bytes,2,opt,name=question,proto3" json:"question,omitempty"`
	Synthesize    *bool                  `protobuf:"varint,3,opt,name=synthesize,proto3,oneof" json:"synthesize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImpactOfRequest) Reset() {
	*x = ImpactOfRequest{}
	mi := &file_lore_v1_lore_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImpactOfRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImpactOfRequest) ProtoMessage() {}

func (x *ImpactOfRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lore_v1_lore_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImpactOfRequest.ProtoReflect.Descriptor instead.
func (*ImpactOfRequest) Descriptor() ([]byte, []int) {
	return file_lore_v1_lore_proto_rawDescGZIP(), []int{6}
}

func (x *ImpactOfRequest) GetRefOrQuery() string {
	if x != nil {
		return x.RefOrQuery
	}
	return ""
}

func (x *ImpactOfRequest) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *ImpactOfRequest) GetSynthesize() bool {
	if x != nil && x.Synthesize != nil {
		return *x.Synthesize
	}
	return false
}

type ImpactOfResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bundle        *EvidenceBundle        `protobuf:"bytes,1,opt,name=bundle,proto3" json:"bundle,omitempty"`
	Synthesis     string                 `protobuf:"bytes,2,opt,name=synthesis,proto3" json:"synthesis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImpactOfResponse) Reset() {
	*x = ImpactOfResponse{}
	mi := &file_lore_v1_lore_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImpactOfResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImpactOfResponse) ProtoMessage() {}

func (x *ImpactOfResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lore_v1_lore_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImpactOfResponse.ProtoReflect.Descriptor instead.
func (*ImpactOfResponse) Descriptor() ([]byte, []int) {
	return file_lore_v1_lore_proto_rawDescGZIP(), []int{7}
}

func (x *ImpactOfResponse) GetBundle() *EvidenceBundle {
	if x != nil {
		return x.Bundle
	}
	return nil
}

func (x *ImpactOfResponse) GetSynthesis() string {
	if x != nil {
		return x.Synthesis
	}
	return ""
}

type HistoryOfRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Repo          string                 `protobuf:"bytes,2,opt,name=repo,proto3" json:"repo,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Before        string                 `protobuf:"bytes,4,opt,name=before,proto3" json:"before,omitempty"`
	Synthesize    *bool                  `protobuf:"varint,5,opt,name=synthesize,proto3,oneof" json:"synthesize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryOfRequest) Reset() {
	*x = HistoryOfRequest{}
	mi := &file_lore_v1_lore_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryOfRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryOfRequest) ProtoMessage() {}

func (x *HistoryOfRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lore_v1_lore_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryOfRequest.ProtoReflect.Descriptor instead.
func (*HistoryOfRequest) Descriptor() ([]byte, []int) {
	return file_lore_v1_lore_proto_rawDescGZIP(), []int{8}
}

func (x *HistoryOfRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *HistoryOfRequest) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *HistoryOfRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *HistoryOfRequest) GetBefore() string {
	if x != nil {
		return x.Before
	}
	return ""
}

func (x *HistoryOfRequest) GetSynthesize() bool {
	if x != nil && x.Synthesize != nil {
		return *x.Synthesize
	}
	return false
}

type HistoryOfResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bundle        *EvidenceBundle        `protobuf:"bytes,1,opt,name=bundle,proto3" json:"bundle,omitempty"`
	Synthesis     string                 `protobuf:"bytes,2,opt,name=synthesis,proto3" json:"synthesis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryOfResponse) Reset() {
	*x = HistoryOfResponse{}
	mi := &file_lore_v1_lore_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryOfResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryOfResponse) ProtoMessage() {}

func (x *HistoryOfResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lore_v1_lore_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryOfResponse.ProtoReflect.Descriptor instead.
func (*HistoryOfResponse) Descriptor() ([]byte, []int) {
	return file_lore_v1_lore_proto_rawDescGZIP(), []int{9}
}

func (x *HistoryOfResponse) GetBundle() *EvidenceBundle {
	if x != nil {
		return x.Bundle
	}
	return nil
}

func (x *HistoryOfResponse) GetSynthesis() string {
	if x != nil {
		return x.Synthesis
	}
	return ""
}

type TriggerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Reembed       bool                   `protobuf:"varint,2,opt,name=reembed,proto3" json:"reembed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerRequest) Reset() {
	*x = TriggerRequest{}
	mi := &file_lore_v1_lore_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerRequest) ProtoMessage() {}

func (x *TriggerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lore_v1_lore_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerRequest.ProtoReflect.Descriptor instead.
func (*TriggerRequest) Descriptor() ([]byte, []int) {
	return file_lore_v1_lore_proto_rawDescGZIP(), []int{10}
}

func (x *TriggerRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *TriggerRequest) GetReembed() bool {
	if x != nil {
		return x.Reembed
	}
	return false
}

type TriggerResponse struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Synced       string                 `protobuf:"bytes,1,opt,name=synced,proto3" json:"synced,omitempty"`
	TookOverFrom *LeaseState            `protobuf:"bytes,2,opt,name=took_over_from,json=tookOverFrom,proto3" json:"took_over_from,omitempty"`
	// Instances that ended their stream early while the round carried on. Empty on
	// a clean round; a populated list is a partial success, not a failure.
	Failures      []*InstanceFailure `protobuf:"bytes,3,rep,name=failures,proto3" json:"failures,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerResponse) Reset() {
	*x = TriggerResponse{}
	mi := &file_lore_v1_lore_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerResponse) ProtoMessage() {}

func (x *TriggerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lore_v1_lore_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerResponse.ProtoReflect.Descriptor instead.
func (*TriggerResponse) Descriptor() ([]byte, []int) {
	return file_lore_v1_lore_proto_rawDescGZIP(), []int{11}
}

func (x *TriggerResponse) GetSynced() string {
	if x != nil {
		return x.Synced
	}
	return ""
}

func (x *TriggerResponse) GetTookOverFrom() *LeaseState {
	if x != nil {
		return x.TookOverFrom
	}
	return nil
}

func (x *TriggerResponse) GetFailures() []*InstanceFailure {
	if x != nil {
		return x.Failures
	}
	return nil
}

type InstanceFailure struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instance      string                 `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstanceFailure) Reset() {
	*x = InstanceFailure{}
	mi := &file_lore_v1_lore_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstanceFailure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstanceFailure) ProtoMessage() {}

func (x *InstanceFailure) ProtoReflect() protoreflect.Message {
	mi := &file_lore_v1_lore_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstanceFailure.ProtoReflect.Descriptor instead.
func (*InstanceFailure) Descriptor() ([]byte, []int) {
	return file_lore_v1_lore_proto_rawDescGZIP(), []int{12}
}

func (x *InstanceFailure) GetInstance() string {
	if x != nil {
		return x.Instance
	}
	return ""
}

func (x *InstanceFailure) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_lore_v1_lore_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lore_v1_lore_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_lore_v1_lore_proto_rawDescGZIP(), []int{13}
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Documents     int64                  `protobuf:"varint,1,opt,name=documents,proto3" json:"documents,omitempty"`
	Chunks        int64                  `protobuf:"varint,2,opt,name=chunks,proto3" json:"chunks,omitempty"`
	Edges         int64                  `protobuf:"varint,3,opt,name=edges,proto3" json:"edges,omitempty"`
	Cursors       []*CursorAge           `protobuf:"bytes,4,rep,name=cursors,proto3" json:"cursors,omitempty"`
	Lease         *LeaseState            `protobuf:"bytes,5,opt,name=lease,proto3" json:"lease,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_lore_v1_lore_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lore_v1_lore_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_lore_v1_lore_proto_rawDescGZIP(), []int{14}
}

func (x *StatusResponse) GetDocuments() int64 {
	if x != nil {
		return x.Documents
	}
	return 0
}

func (x *StatusResponse) GetChunks() int64 {
	if x != nil {
		return x.Chunks
	}
	return 0
}

func (x *StatusResponse) GetEdges() int64 {
	if x != nil {
		return x.Edges
	}
	return 0
}

func (x *StatusResponse) GetCursors() []*CursorAge {
	if x != nil {
		return x.Cursors
	}
	return nil
}

func (x *StatusResponse) GetLease() *LeaseState {
	if x != nil {
		return x.Lease
	}
	return nil
}

type WatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRequest) Reset() {
	*x = WatchRequest{}
	mi := &file_lore_v1_lore_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequest) ProtoMessage() {}

func (x *WatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lore_v1_lore_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRequest.ProtoReflect.Descriptor instead.
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return file_lore_v1_lore_proto_rawDescGZIP(), []int{15}
}

type SyncEvent struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Source string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Phase  SyncPhase              `protobuf:"varint,2,opt,name=phase,proto3,enum=lore.v1.SyncPhase" json:"phase,omitempty"`
	// Cumulative round totals known at emit time, monotonic within a round, never per-event deltas.
	Documents     int64                  `protobuf:"varint,3,opt,name=documents,proto3" json:"documents,omitempty"`
	Chunks        int64                  `protobuf:"varint,4,opt,name=chunks,proto3" json:"chunks,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	At            *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=at,proto3" json:"at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncEvent) Reset() {
	*x = SyncEvent{}
	mi := &file_lore_v1_lore_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncEvent) ProtoMessage() {}

func (x *SyncEvent) ProtoReflect() protoreflect.Message {
	mi := &file_lore_v1_lore_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncEvent.ProtoReflect.Descriptor instead.
func (*SyncEvent) Descriptor() ([]byte, []int) {
	return file_lore_v1_lore_proto_rawDescGZIP(), []int{16}
}

func (x *SyncEvent) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *SyncEvent) GetPhase() SyncPhase {
	if x != nil {
		return x.Phase
	}
	return SyncPhase_SYNC_PHASE_UNSPECIFIED
}

func (x *SyncEvent) GetDocuments() int64 {
	if x != nil {
		return x.Documents
	}
	return 0
}

func (x *SyncEvent) GetChunks() int64 {
	if x != nil {
		return x.Chunks
	}
	return 0
}

func (x *SyncEvent) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *SyncEvent) GetAt() *timestamppb.Timestamp {
	if x != nil {
		return x.At
	}
	return nil
}

type CursorAge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CursorAge) Reset() {
	*x = CursorAge{}
	mi := &file_lore_v1_lore_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CursorAge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CursorAge) ProtoMessage() {}

func (x *CursorAge) ProtoReflect() protoreflect.Message {
	mi := &file_lore_v1_lore_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CursorAge.ProtoReflect.Descriptor instead.
func (*CursorAge) Descriptor() ([]byte, []int) {
	return file_lore_v1_lore_proto_rawDescGZIP(), []int{17}
}

func (x *CursorAge) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *CursorAge) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type LeaseState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Holder        string                 `protobuf:"bytes,1,opt,name=holder,proto3" json:"holder,omitempty"`
	AcquiredAt    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=acquired_at,json=acquiredAt,proto3" json:"acquired_at,omitempty"`
	HeartbeatAt   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=heartbeat_at,json=heartbeatAt,proto3" json:"heartbeat_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaseState) Reset() {
	*x = LeaseState{}
	mi := &file_lore_v1_lore_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaseState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaseState) ProtoMessage() {}

func (x *LeaseState) ProtoReflect() protoreflect.Message {
	mi := &file_lore_v1_lore_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaseState.ProtoReflect.Descriptor instead.
func (*LeaseState) Descriptor() ([]byte, []int) {
	return file_lore_v1_lore_proto_rawDescGZIP(), []int{18}
}

func (x *LeaseState) GetHolder() string {
	if x != nil {
		return x.Holder
	}
	return ""
}

func (x *LeaseState) GetAcquiredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.AcquiredAt
	}
	return nil
}

func (x *LeaseState) GetHeartbeatAt() *timestamppb.Timestamp {
	if x != nil {
		return x.HeartbeatAt
	}
	return nil
}

type EvidenceBundle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Question      string                 `protobuf:"bytes,1,opt,name=question,proto3" json:"question,omitempty"`
	Anchor        *Anchor                `protobuf:"bytes,2,opt,name=anchor,proto3" json:"anchor,omitempty"`
	Nodes         []*EvidenceNode        `protobuf:"bytes,3,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Chains        []*Chain               `protobuf:"bytes,4,rep,name=chains,proto3" json:"chains,omitempty"`
	Gaps          []string               `protobuf:"bytes,5,rep,name=gaps,proto3" json:"gaps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvidenceBundle) Reset() {
	*x = EvidenceBundle{}
	mi := &file_lore_v1_lore_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvidenceBundle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvidenceBundle) ProtoMessage() {}

func (x *EvidenceBundle) ProtoReflect() protoreflect.Message {
	mi := &file_lore_v1_lore_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvidenceBundle.ProtoReflect.Descriptor instead.
func (*EvidenceBundle) Descriptor() ([]byte, []int) {
	return file_lore_v1_lore_proto_rawDescGZIP(), []int{19}
}

func (x *EvidenceBundle) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *EvidenceBundle) GetAnchor() *Anchor {
	if x != nil {
		return x.Anchor
	}
	return nil
}

func (x *EvidenceBundle) GetNodes() []*EvidenceNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *EvidenceBundle) GetChains() []*Chain {
	if x != nil {
		return x.Chains
	}
	return nil
}

func (x *EvidenceBundle) GetGaps() []string {
	if x != nil {
		return x.Gaps
	}
	return nil
}

type Chain struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocIds        []string               `protobuf:"bytes,1,rep,name=doc_ids,json=docIds,proto3" json:"doc_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chain) Reset() {
	*x = Chain{}
	mi := &file_lore_v1_lore_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chain) ProtoMessage() {}

func (x *Chain) ProtoReflect() protoreflect.Message {
	mi := &file_lore_v1_lore_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chain.ProtoReflect.Descriptor instead.
func (*Chain) Descriptor() ([]byte, []int) {
	return file_lore_v1_lore_proto_rawDescGZIP(), []int{20}
}

func (x *Chain) GetDocIds() []string {
	if x != nil {
		return x.DocIds
	}
	return nil
}

type Anchor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kinds         []AnchorKind           `protobuf:"varint,1,rep,packed,name=kinds,proto3,enum=lore.v1.AnchorKind" json:"kinds,omitempty"`
	Query         string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	Code          *CodeAnchor            `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Doc           *DocRef                `protobuf:"bytes,4,opt,name=doc,proto3" json:"doc,omitempty"`
	Window        *TimeWindow            `protobuf:"bytes,5,opt,name=window,proto3" json:"window,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Anchor) Reset() {
	*x = Anchor{}
	mi := &file_lore_v1_lore_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Anchor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Anchor) ProtoMessage() {}

func (x *Anchor) ProtoReflect() protoreflect.Message {
	mi := &file_lore_v1_lore_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Anchor.ProtoReflect.Descriptor instead.
func (*Anchor) Descriptor() ([]byte, []int) {
	return file_lore_v1_lore_proto_rawDescGZIP(), []int{21}
}

func (x *Anchor) GetKinds() []AnchorKind {
	if x != nil {
		return x.Kinds
	}
	return nil
}

func (x *Anchor) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *Anchor) GetCode() *CodeAnchor {
	if x != nil {
		return x.Code
	}
	return nil
}

func (x *Anchor) GetDoc() *DocRef {
	if x != nil {
		return x.Doc
	}
	return nil
}

func (x *Anchor) GetWindow() *TimeWindow {
	if x != nil {
		return x.Window
	}
	return nil
}

// Line numbers are 1-based, so an omitted line_start/line_end means a whole-file anchor.
type CodeAnchor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repo          string                 `protobuf:"bytes,1,opt,name=repo,proto3" json:"repo,omitempty"`
	File          string                 `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty"`
	LineStart     int32                  `protobuf:"varint,3,opt,name=line_start,json=lineStart,proto3" json:"line_start,omitempty"`
	LineEnd       int32                  `protobuf:"varint,4,opt,name=line_end,json=lineEnd,proto3" json:"line_end,omitempty"`
	BlamedShas    []string               `protobuf:"bytes,5,rep,name=blamed_shas,json=blamedShas,proto3" json:"blamed_shas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CodeAnchor) Reset() {
	*x = CodeAnchor{}
	mi := &file_lore_v1_lore_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CodeAnchor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CodeAnchor) ProtoMessage() {}

func (x *CodeAnchor) ProtoReflect() protoreflect.Message {
	mi := &file_lore_v1_lore_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CodeAnchor.ProtoReflect.Descriptor instead.
func (*CodeAnchor) Descriptor() ([]byte, []int) {
	return file_lore_v1_lore_proto_rawDescGZIP(), []int{22}
}

func (x *CodeAnchor) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *CodeAnchor) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *CodeAnchor) GetLineStart() int32 {
	if x != nil {
		return x.LineStart
	}
	return 0
}

func (x *CodeAnchor) GetLineEnd() int32 {
	if x != nil {
		return x.LineEnd
	}
	return 0
}

func (x *CodeAnchor) GetBlamedShas() []string {
	if x != nil {
		return x.BlamedShas
	}
	return nil
}

type DocRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocRef) Reset() {
	*x = DocRef{}
	mi := &file_lore_v1_lore_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocRef) ProtoMessage() {}

func (x *DocRef) ProtoReflect() protoreflect.Message {
	mi := &file_lore_v1_lore_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocRef.ProtoReflect.Descriptor instead.
func (*DocRef) Descriptor() ([]byte, []int) {
	return file_lore_v1_lore_proto_rawDescGZIP(), []int{23}
}

func (x *DocRef) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DocRef) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *DocRef) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *DocRef) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type TimeWindow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Derivation    string                 `protobuf:"bytes,3,opt,name=derivation,proto3" json:"derivation,omitempty"`
	AnchoredBy    string                 `protobuf:"bytes,4,opt,name=anchored_by,json=anchoredBy,proto3" json:"anchored_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeWindow) Reset() {
	*x = TimeWindow{}
	mi := &file_lore_v1_lore_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeWindow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeWindow) ProtoMessage() {}

func (x *TimeWindow) ProtoReflect() protoreflect.Message {
	mi := &file_lore_v1_lore_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeWindow.ProtoReflect.Descriptor instead.
func (*TimeWindow) Descriptor() ([]byte, []int) {
	return file_lore_v1_lore_proto_rawDescGZIP(), []int{24}
}

func (x *TimeWindow) GetFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *TimeWindow) GetTo() *timestamppb.Timestamp {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *TimeWindow) GetDerivation() string {
	if x != nil {
		return x.Derivation
	}
	return ""
}

func (x *TimeWindow) GetAnchoredBy() string {
	if x != nil {
		return x.AnchoredBy
	}
	return ""
}

type EvidenceNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Doc           *DocumentMeta          `protobuf:"bytes,1,opt,name=doc,proto3" json:"doc,omitempty"`
	Excerpt       string                 `protobuf:"bytes,2,opt,name=excerpt,proto3" json:"excerpt,omitempty"`
	Role          NodeRole               `protobuf:"varint,3,opt,name=role,proto3,enum=lore.v1.NodeRole" json:"role,omitempty"`
	Score         float32                `protobuf:"fixed32,4,opt,name=score,proto3" json:"score,omitempty"`
	Via           []*Edge                `protobuf:"bytes,5,rep,name=via,proto3" json:"via,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvidenceNode) Reset() {
	*x = EvidenceNode{}
	mi := &file_lore_v1_lore_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvidenceNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvidenceNode) ProtoMessage() {}

func (x *EvidenceNode) ProtoReflect() protoreflect.Message {
	mi := &file_lore_v1_lore_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvidenceNode.ProtoReflect.Descriptor instead.
func (*EvidenceNode) Descriptor() ([]byte, []int) {
	return file_lore_v1_lore_proto_rawDescGZIP(), []int{25}
}

func (x *EvidenceNode) GetDoc() *DocumentMeta {
	if x != nil {
		return x.Doc
	}
	return nil
}

func (x *EvidenceNode) GetExcerpt() string {
	if x != nil {
		return x.Excerpt
	}
	return ""
}

func (x *EvidenceNode) GetRole() NodeRole {
	if x != nil {
		return x.Role
	}
	return NodeRole_NODE_ROLE_UNSPECIFIED
}

func (x *EvidenceNode) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *EvidenceNode) GetVia() []*Edge {
	if x != nil {
		return x.Via
	}
	return nil
}

type DocumentMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Author        string                 `protobuf:"bytes,5,opt,name=author,proto3" json:"author,omitempty"`
	Url           string                 `protobuf:"bytes,6,opt,name=url,proto3" json:"url,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentMeta) Reset() {
	*x = DocumentMeta{}
	mi := &file_lore_v1_lore_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentMeta) ProtoMessage() {}

func (x *DocumentMeta) ProtoReflect() protoreflect.Message {
	mi := &file_lore_v1_lore_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentMeta.ProtoReflect.Descriptor instead.
func (*DocumentMeta) Descriptor() ([]byte, []int) {
	return file_lore_v1_lore_proto_rawDescGZIP(), []int{26}
}

func (x *DocumentMeta) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DocumentMeta) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *DocumentMeta) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *DocumentMeta) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *DocumentMeta) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *DocumentMeta) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *DocumentMeta) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *DocumentMeta) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Edge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Src           string                 `protobuf:"bytes,1,opt,name=src,proto3" json:"src,omitempty"`
	Dst           string                 `protobuf:"bytes,2,opt,name=dst,proto3" json:"dst,omitempty"`
	Kind          EdgeKind               `protobuf:"varint,3,opt,name=kind,proto3,enum=lore.v1.EdgeKind" json:"kind,omitempty"`
	Confidence    float32                `protobuf:"fixed32,4,opt,name=confidence,proto3" json:"confidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Edge) Reset() {
	*x = Edge{}
	mi := &file_lore_v1_lore_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Edge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Edge) ProtoMessage() {}

func (x *Edge) ProtoReflect() protoreflect.Message {
	mi := &file_lore_v1_lore_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Edge.ProtoReflect.Descriptor instead.
func (*Edge) Descriptor() ([]byte, []int) {
	return file_lore_v1_lore_proto_rawDescGZIP(), []int{27}
}

func (x *Edge) GetSrc() string {
	if x != nil {
		return x.Src
	}
	return ""
}

func (x *Edge) GetDst() string {
	if x != nil {
		return x.Dst
	}
	return ""
}

func (x *Edge) GetKind() EdgeKind {
	if x != nil {
		return x.Kind
	}
	return EdgeKind_EDGE_KIND_UNSPECIFIED
}

func (x *Edge) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

var File_lore_v1_lore_proto protoreflect.FileDescriptor

const file_lore_v1_lore_proto_rawDesc = "" +
	"\n" +
	"\x12lore/v1/lore.proto\x12\alore.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa8\x02\n" +
	"\x13FindDecisionRequest\x12\x1a\n" +
	"\bquestion\x18\x01 \x01(\tR\bquestion\x12\x16\n" +
	"\x06around\x18\x02 \x01(\tR\x06around\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12\x12\n" +
	"\x04repo\x18\x04 \x01(\tR\x04repo\x12\x19\n" +
	"\bdoc_type\x18\x05 \x01(\tR\adocType\x120\n" +
	"\x05since\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x05since\x120\n" +
	"\x05until\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x05until\x12#\n" +
	"\n" +
	"synthesize\x18\b \x01(\bH\x00R\n" +
	"synthesize\x88\x01\x01B\r\n" +
	"\v_synthesize\"e\n" +
	"\x14FindDecisionResponse\x12/\n" +
	"\x06bundle\x18\x01 \x01(\v2\x17.lore.v1.EvidenceBundleR\x06bundle\x12\x1c\n" +
	"\tsynthesis\x18\x02 \x01(\tR\tsynthesis\"\xbe\x01\n" +
	"\n" +
	"WhyRequest\x12\x12\n" +
	"\x04repo\x18\x01 \x01(\tR\x04repo\x12\x12\n" +
	"\x04file\x18\x02 \x01(\tR\x04file\x12\x1d\n" +
	"\n" +
	"line_start\x18\x03 \x01(\x05R\tlineStart\x12\x19\n" +
	"\bline_end\x18\x04 \x01(\x05R\alineEnd\x12\x1a\n" +
	"\bquestion\x18\x05 \x01(\tR\bquestion\x12#\n" +
	"\n" +
	"synthesize\x18\x06 \x01(\bH\x00R\n" +
	"synthesize\x88\x01\x01B\r\n" +
	"\v_synthesize\"\\\n" +
	"\vWhyResponse\x12/\n" +
	"\x06bundle\x18\x01 \x01(\v2\x17.lore.v1.EvidenceBundleR\x06bundle\x12\x1c\n" +
	"\tsynthesis\x18\x02 \x01(\tR\tsynthesis\"\x9c\x01\n" +
	"\fTraceRequest\x12\x10\n" +
	"\x03ref\x18\x01 \x01(\tR\x03ref\x120\n" +
	"\tdirection\x18\x02 \x01(\x0e2\x12.lore.v1.DirectionR\tdirection\x12\x14\n" +
	"\x05depth\x18\x03 \x01(\x05R\x05depth\x12#\n" +
	"\n" +
	"synthesize\x18\x04 \x01(\bH\x00R\n" +
	"synthesize\x88\x01\x01B\r\n" +
	"\v_synthesize\"^\n" +
	"\rTraceResponse\x12/\n" +
	"\x06bundle\x18\x01 \x01(\v2\x17.lore.v1.EvidenceBundleR\x06bundle\x12\x1c\n" +
	"\tsynthesis\x18\x02 \x01(\tR\tsynthesis\"\x83\x01\n" +
	"\x0fImpactOfRequest\x12 \n" +
	"\fref_or_query\x18\x01 \x01(\tR\n" +
	"refOrQuery\x12\x1a\n" +
	"\bquestion\x18\x02 \x01(\tR\bquestion\x12#\n" +
	"\n" +
	"synthesize\x18\x03 \x01(\bH\x00R\n" +
	"synthesize\x88\x01\x01B\r\n" +
	"\v_synthesize\"a\n" +
	"\x10ImpactOfResponse\x12/\n" +
	"\x06bundle\x18\x01 \x01(\v2\x17.lore.v1.EvidenceBundleR\x06bundle\x12\x1c\n" +
	"\tsynthesis\x18\x02 \x01(\tR\tsynthesis\"\x9c\x01\n" +
	"\x10HistoryOfRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04repo\x18\x02 \x01(\tR\x04repo\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06before\x18\x04 \x01(\tR\x06before\x12#\n" +
	"\n" +
	"synthesize\x18\x05 \x01(\bH\x00R\n" +
	"synthesize\x88\x01\x01B\r\n" +
	"\v_synthesize\"b\n" +
	"\x11HistoryOfResponse\x12/\n" +
	"\x06bundle\x18\x01 \x01(\v2\x17.lore.v1.EvidenceBundleR\x06bundle\x12\x1c\n" +
	"\tsynthesis\x18\x02 \x01(\tR\tsynthesis\"B\n" +
	"\x0eTriggerRequest\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x18\n" +
	"\areembed\x18\x02 \x01(\bR\areembed\"\x9a\x01\n" +
	"\x0fTriggerResponse\x12\x16\n" +
	"\x06synced\x18\x01 \x01(\tR\x06synced\x129\n" +
	"\x0etook_over_from\x18\x02 \x01(\v2\x13.lore.v1.LeaseStateR\ftookOverFrom\x124\n" +
	"\bfailures\x18\x03 \x03(\v2\x18.lore.v1.InstanceFailureR\bfailures\"C\n" +
	"\x0fInstanceFailure\x12\x1a\n" +
	"\binstance\x18\x01 \x01(\tR\binstance\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x0f\n" +
	"\rStatusRequest\"\xb5\x01\n" +
	"\x0eStatusResponse\x12\x1c\n" +
	"\tdocuments\x18\x01 \x01(\x03R\tdocuments\x12\x16\n" +
	"\x06chunks\x18\x02 \x01(\x03R\x06chunks\x12\x14\n" +
	"\x05edges\x18\x03 \x01(\x03R\x05edges\x12,\n" +
	"\acursors\x18\x04 \x03(\v2\x12.lore.v1.CursorAgeR\acursors\x12)\n" +
	"\x05lease\x18\x05 \x01(\v2\x13.lore.v1.LeaseStateR\x05lease\"\x0e\n" +
	"\fWatchRequest\"\xc5\x01\n" +
	"\tSyncEvent\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12(\n" +
	"\x05phase\x18\x02 \x01(\x0e2\x12.lore.v1.SyncPhaseR\x05phase\x12\x1c\n" +
	"\tdocuments\x18\x03 \x01(\x03R\tdocuments\x12\x16\n" +
	"\x06chunks\x18\x04 \x01(\x03R\x06chunks\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x12*\n" +
	"\x02at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x02at\"^\n" +
	"\tCursorAge\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x129\n" +
	"\n" +
	"updated_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xa0\x01\n" +
	"\n" +
	"LeaseState\x12\x16\n" +
	"\x06holder\x18\x01 \x01(\tR\x06holder\x12;\n" +
	"\vacquired_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"acquiredAt\x12=\n" +
	"\fheartbeat_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vheartbeatAt\"\xbe\x01\n" +
	"\x0eEvidenceBundle\x12\x1a\n" +
	"\bquestion\x18\x01 \x01(\tR\bquestion\x12'\n" +
	"\x06anchor\x18\x02 \x01(\v2\x0f.lore.v1.AnchorR\x06anchor\x12+\n" +
	"\x05nodes\x18\x03 \x03(\v2\x15.lore.v1.EvidenceNodeR\x05nodes\x12&\n" +
	"\x06chains\x18\x04 \x03(\v2\x0e.lore.v1.ChainR\x06chains\x12\x12\n" +
	"\x04gaps\x18\x05 \x03(\tR\x04gaps\" \n" +
	"\x05Chain\x12\x17\n" +
	"\adoc_ids\x18\x01 \x03(\tR\x06docIds\"\xc2\x01\n" +
	"\x06Anchor\x12)\n" +
	"\x05kinds\x18\x01 \x03(\x0e2\x13.lore.v1.AnchorKindR\x05kinds\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12'\n" +
	"\x04code\x18\x03 \x01(\v2\x13.lore.v1.CodeAnchorR\x04code\x12!\n" +
	"\x03doc\x18\x04 \x01(\v2\x0f.lore.v1.DocRefR\x03doc\x12+\n" +
	"\x06window\x18\x05 \x01(\v2\x13.lore.v1.TimeWindowR\x06window\"\x8f\x01\n" +
	"\n" +
	"CodeAnchor\x12\x12\n" +
	"\x04repo\x18\x01 \x01(\tR\x04repo\x12\x12\n" +
	"\x04file\x18\x02 \x01(\tR\x04file\x12\x1d\n" +
	"\n" +
	"line_start\x18\x03 \x01(\x05R\tlineStart\x12\x19\n" +
	"\bline_end\x18\x04 \x01(\x05R\alineEnd\x12\x1f\n" +
	"\vblamed_shas\x18\x05 \x03(\tR\n" +
	"blamedShas\"{\n" +
	"\x06DocRef\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xa9\x01\n" +
	"\n" +
	"TimeWindow\x12.\n" +
	"\x04from\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04from\x12*\n" +
	"\x02to\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x02to\x12\x1e\n" +
	"\n" +
	"derivation\x18\x03 \x01(\tR\n" +
	"derivation\x12\x1f\n" +
	"\vanchored_by\x18\x04 \x01(\tR\n" +
	"anchoredBy\"\xaf\x01\n" +
	"\fEvidenceNode\x12'\n" +
	"\x03doc\x18\x01 \x01(\v2\x15.lore.v1.DocumentMetaR\x03doc\x12\x18\n" +
	"\aexcerpt\x18\x02 \x01(\tR\aexcerpt\x12%\n" +
	"\x04role\x18\x03 \x01(\x0e2\x11.lore.v1.NodeRoleR\x04role\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x02R\x05score\x12\x1f\n" +
	"\x03via\x18\x05 \x03(\v2\r.lore.v1.EdgeR\x03via\"\x80\x02\n" +
	"\fDocumentMeta\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x16\n" +
	"\x06author\x18\x05 \x01(\tR\x06author\x12\x10\n" +
	"\x03url\x18\x06 \x01(\tR\x03url\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"q\n" +
	"\x04Edge\x12\x10\n" +
	"\x03src\x18\x01 \x01(\tR\x03src\x12\x10\n" +
	"\x03dst\x18\x02 \x01(\tR\x03dst\x12%\n" +
	"\x04kind\x18\x03 \x01(\x0e2\x11.lore.v1.EdgeKindR\x04kind\x12\x1e\n" +
	"\n" +
	"confidence\x18\x04 \x01(\x02R\n" +
	"confidence*\x92\x01\n" +
	"\n" +
	"AnchorKind\x12\x1b\n" +
	"\x17ANCHOR_KIND_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11ANCHOR_KIND_QUERY\x10\x01\x12\x19\n" +
	"\x15ANCHOR_KIND_CODE_SPAN\x10\x02\x12\x18\n" +
	"\x14ANCHOR_KIND_DOCUMENT\x10\x03\x12\x1b\n" +
	"\x17ANCHOR_KIND_TIME_WINDOW\x10\x04*\xfe\x01\n" +
	"\bNodeRole\x12\x19\n" +
	"\x15NODE_ROLE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eNODE_ROLE_SEED\x10\x01\x12\x1b\n" +
	"\x17NODE_ROLE_BLAMED_COMMIT\x10\x02\x12\x1b\n" +
	"\x17NODE_ROLE_REVIEW_THREAD\x10\x03\x12\x1b\n" +
	"\x17NODE_ROLE_LINKED_TICKET\x10\x04\x12\x18\n" +
	"\x14NODE_ROLE_DESIGN_DOC\x10\x05\x12\x17\n" +
	"\x13NODE_ROLE_FOLLOW_UP\x10\x06\x12\x1c\n" +
	"\x18NODE_ROLE_SEMANTIC_MATCH\x10\a\x12\x1b\n" +
	"\x17NODE_ROLE_LINKED_CHANGE\x10\b*\xd4\x01\n" +
	"\bEdgeKind\x12\x19\n" +
	"\x15EDGE_KIND_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16EDGE_KIND_COMMIT_IN_PR\x10\x01\x12\x1d\n" +
	"\x19EDGE_KIND_PR_CLOSES_ISSUE\x10\x02\x12\x1c\n" +
	"\x18EDGE_KIND_REFERENCES_DOC\x10\x03\x12\x1d\n" +
	"\x19EDGE_KIND_MENTIONS_COMMIT\x10\x04\x12\x1b\n" +
	"\x17EDGE_KIND_MENTIONS_PATH\x10\x05\x12\x18\n" +
	"\x14EDGE_KIND_SUPERSEDES\x10\x06*_\n" +
	"\tDirection\x12\x19\n" +
	"\x15DIRECTION_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rDIRECTION_OUT\x10\x01\x12\x10\n" +
	"\fDIRECTION_IN\x10\x02\x12\x12\n" +
	"\x0eDIRECTION_BOTH\x10\x03*\xf9\x01\n" +
	"\tSyncPhase\x12\x1a\n" +
	"\x16SYNC_PHASE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18SYNC_PHASE_ROUND_STARTED\x10\x01\x12\x1b\n" +
	"\x17SYNC_PHASE_BATCH_STORED\x10\x02\x12\x1d\n" +
	"\x19SYNC_PHASE_CHUNKS_INDEXED\x10\x03\x12!\n" +
	"\x1dSYNC_PHASE_CONNECTOR_FINISHED\x10\x04\x12\x1d\n" +
	"\x19SYNC_PHASE_PENDING_LINKED\x10\x05\x12\x1d\n" +
	"\x19SYNC_PHASE_ROUND_FINISHED\x10\x06\x12\x15\n" +
	"\x11SYNC_PHASE_FAILED\x10\a2\xca\x02\n" +
	"\fQueryService\x12K\n" +
	"\fFindDecision\x12\x1c.lore.v1.FindDecisionRequest\x1a\x1d.lore.v1.FindDecisionResponse\x120\n" +
	"\x03Why\x12\x13.lore.v1.WhyRequest\x1a\x14.lore.v1.WhyResponse\x126\n" +
	"\x05Trace\x12\x15.lore.v1.TraceRequest\x1a\x16.lore.v1.TraceResponse\x12?\n" +
	"\bImpactOf\x12\x18.lore.v1.ImpactOfRequest\x1a\x19.lore.v1.ImpactOfResponse\x12B\n" +
	"\tHistoryOf\x12\x19.lore.v1.HistoryOfRequest\x1a\x1a.lore.v1.HistoryOfResponse2\xbc\x01\n" +
	"\vSyncService\x12<\n" +
	"\aTrigger\x12\x17.lore.v1.TriggerRequest\x1a\x18.lore.v1.TriggerResponse\x129\n" +
	"\x06Status\x12\x16.lore.v1.StatusRequest\x1a\x17.lore.v1.StatusResponse\x124\n" +
	"\x05Watch\x12\x15.lore.v1.WatchRequest\x1a\x12.lore.v1.SyncEvent0\x01B4Z2github.com/setthasit/Lore/api/proto/lore/v1;lorev1b\x06proto3"

var (
	file_lore_v1_lore_proto_rawDescOnce sync.Once
	file_lore_v1_lore_proto_rawDescData []byte
)

func file_lore_v1_lore_proto_rawDescGZIP() []byte {
	file_lore_v1_lore_proto_rawDescOnce.Do(func() {
		file_lore_v1_lore_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lore_v1_lore_proto_rawDesc), len(file_lore_v1_lore_proto_rawDesc)))
	})
	return file_lore_v1_lore_proto_rawDescData
}

var file_lore_v1_lore_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_lore_v1_lore_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_lore_v1_lore_proto_goTypes = []any{
	(AnchorKind)(0),               // 0: lore.v1.AnchorKind
	(NodeRole)(0),                 // 1: lore.v1.NodeRole
	(EdgeKind)(0),                 // 2: lore.v1.EdgeKind
	(Direction)(0),                // 3: lore.v1.Direction
	(SyncPhase)(0),                // 4: lore.v1.SyncPhase
	(*FindDecisionRequest)(nil),   // 5: lore.v1.FindDecisionRequest
	(*FindDecisionResponse)(nil),  // 6: lore.v1.FindDecisionResponse
	(*WhyRequest)(nil),            // 7: lore.v1.WhyRequest
	(*WhyResponse)(nil),           // 8: lore.v1.WhyResponse
	(*TraceRequest)(nil),          // 9: lore.v1.TraceRequest
	(*TraceResponse)(nil),         // 10: lore.v1.TraceResponse
	(*ImpactOfRequest)(nil),       // 11: lore.v1.ImpactOfRequest
	(*ImpactOfResponse)(nil),      // 12: lore.v1.ImpactOfResponse
	(*HistoryOfRequest)(nil),      // 13: lore.v1.HistoryOfRequest
	(*HistoryOfResponse)(nil),     // 14: lore.v1.HistoryOfResponse
	(*TriggerRequest)(nil),        // 15: lore.v1.TriggerRequest
	(*TriggerResponse)(nil),       // 16: lore.v1.TriggerResponse
	(*InstanceFailure)(nil),       // 17: lore.v1.InstanceFailure
	(*StatusRequest)(nil),         // 18: lore.v1.StatusRequest
	(*StatusResponse)(nil),        // 19: lore.v1.StatusResponse
	(*WatchRequest)(nil),          // 20: lore.v1.WatchRequest
	(*SyncEvent)(nil),             // 21: lore.v1.SyncEvent
	(*CursorAge)(nil),             // 22: lore.v1.CursorAge
	(*LeaseState)(nil),            // 23: lore.v1.LeaseState
	(*EvidenceBundle)(nil),        // 24: lore.v1.EvidenceBundle
	(*Chain)(nil),                 // 25: lore.v1.Chain
	(*Anchor)(nil),                // 26: lore.v1.Anchor
	(*CodeAnchor)(nil),            // 27: lore.v1.CodeAnchor
	(*DocRef)(nil),                // 28: lore.v1.DocRef
	(*TimeWindow)(nil),            // 29: lore.v1.TimeWindow
	(*EvidenceNode)(nil),          // 30: lore.v1.EvidenceNode
	(*DocumentMeta)(nil),          // 31: lore.v1.DocumentMeta
	(*Edge)(nil),                  // 32: lore.v1.Edge
	(*timestamppb.Timestamp)(nil), // 33: google.protobuf.Timestamp
}
var file_lore_v1_lore_proto_depIdxs = []int32{
	33, // 0: lore.v1.FindDecisionRequest.since:type_name -> google.protobuf.Timestamp
	33, // 1: lore.v1.FindDecisionRequest.until:type_name -> google.protobuf.Timestamp
	24, // 2: lore.v1.FindDecisionResponse.bundle:type_name -> lore.v1.EvidenceBundle
	24, // 3: lore.v1.WhyResponse.bundle:type_name -> lore.v1.EvidenceBundle
	3,  // 4: lore.v1.TraceRequest.direction:type_name -> lore.v1.Direction
	24, // 5: lore.v1.TraceResponse.bundle:type_name -> lore.v1.EvidenceBundle
	24, // 6: lore.v1.ImpactOfResponse.bundle:type_name -> lore.v1.EvidenceBundle
	24, // 7: lore.v1.HistoryOfResponse.bundle:type_name -> lore.v1.EvidenceBundle
	23, // 8: lore.v1.TriggerResponse.took_over_from:type_name -> lore.v1.LeaseState
	17, // 9: lore.v1.TriggerResponse.failures:type_name -> lore.v1.InstanceFailure
	22, // 10: lore.v1.StatusResponse.cursors:type_name -> lore.v1.CursorAge
	23, // 11: lore.v1.StatusResponse.lease:type_name -> lore.v1.LeaseState
	4,  // 12: lore.v1.SyncEvent.phase:type_name -> lore.v1.SyncPhase
	33, // 13: lore.v1.SyncEvent.at:type_name -> google.protobuf.Timestamp
	33, // 14: lore.v1.CursorAge.updated_at:type_name -> google.protobuf.Timestamp
	33, // 15: lore.v1.LeaseState.acquired_at:type_name -> google.protobuf.Timestamp
	33, // 16: lore.v1.LeaseState.heartbeat_at:type_name -> google.protobuf.Timestamp
	26, // 17: lore.v1.EvidenceBundle.anchor:type_name -> lore.v1.Anchor
	30, // 18: lore.v1.EvidenceBundle.nodes:type_name -> lore.v1.EvidenceNode
	25, // 19: lore.v1.EvidenceBundle.chains:type_name -> lore.v1.Chain
	0,  // 20: lore.v1.Anchor.kinds:type_name -> lore.v1.AnchorKind
	27, // 21: lore.v1.Anchor.code:type_name -> lore.v1.CodeAnchor
	28, // 22: lore.v1.Anchor.doc:type_name -> lore.v1.DocRef
	29, // 23: lore.v1.Anchor.window:type_name -> lore.v1.TimeWindow
	33, // 24: lore.v1.DocRef.created_at:type_name -> google.protobuf.Timestamp
	33, // 25: lore.v1.TimeWindow.from:type_name -> google.protobuf.Timestamp
	33, // 26: lore.v1.TimeWindow.to:type_name -> google.protobuf.Timestamp
	31, // 27: lore.v1.EvidenceNode.doc:type_name -> lore.v1.DocumentMeta
	1,  // 28: lore.v1.EvidenceNode.role:type_name -> lore.v1.NodeRole
	32, // 29: lore.v1.EvidenceNode.via:type_name -> lore.v1.Edge
	33, // 30: lore.v1.DocumentMeta.created_at:type_name -> google.protobuf.Timestamp
	33, // 31: lore.v1.DocumentMeta.updated_at:type_name -> google.protobuf.Timestamp
	2,  // 32: lore.v1.Edge.kind:type_name -> lore.v1.EdgeKind
	5,  // 33: lore.v1.QueryService.FindDecision:input_type -> lore.v1.FindDecisionRequest
	7,  // 34: lore.v1.QueryService.Why:input_type -> lore.v1.WhyRequest
	9,  // 35: lore.v1.QueryService.Trace:input_type -> lore.v1.TraceRequest
	11, // 36: lore.v1.QueryService.ImpactOf:input_type -> lore.v1.ImpactOfRequest
	13, // 37: lore.v1.QueryService.HistoryOf:input_type -> lore.v1.HistoryOfRequest
	15, // 38: lore.v1.SyncService.Trigger:input_type -> lore.v1.TriggerRequest
	18, // 39: lore.v1.SyncService.Status:input_type -> lore.v1.StatusRequest
	20, // 40: lore.v1.SyncService.Watch:input_type -> lore.v1.WatchRequest
	6,  // 41: lore.v1.QueryService.FindDecision:output_type -> lore.v1.FindDecisionResponse
	8,  // 42: lore.v1.QueryService.Why:output_type -> lore.v1.WhyResponse
	10, // 43: lore.v1.QueryService.Trace:output_type -> lore.v1.TraceResponse
	12, // 44: lore.v1.QueryService.ImpactOf:output_type -> lore.v1.ImpactOfResponse
	14, // 45: lore.v1.QueryService.HistoryOf:output_type -> lore.v1.HistoryOfResponse
	16, // 46: lore.v1.SyncService.Trigger:output_type -> lore.v1.TriggerResponse
	19, // 47: lore.v1.SyncService.Status:output_type -> lore.v1.StatusResponse
	21, // 48: lore.v1.SyncService.Watch:output_type -> lore.v1.SyncEvent
	41, // [41:49] is the sub-list for method output_type
	33, // [33:41] is the sub-list for method input_type
	33, // [33:33] is the sub-list for extension type_name
	33, // [33:33] is the sub-list for extension extendee
	0,  // [0:33] is the sub-list for field type_name
}

func init() { file_lore_v1_lore_proto_init() }
func file_lore_v1_lore_proto_init() {
	if File_lore_v1_lore_proto != nil {
		return
	}
	file_lore_v1_lore_proto_msgTypes[0].OneofWrappers = []any{}
	file_lore_v1_lore_proto_msgTypes[2].OneofWrappers = []any{}
	file_lore_v1_lore_proto_msgTypes[4].OneofWrappers = []any{}
	file_lore_v1_lore_proto_msgTypes[6].OneofWrappers = []any{}
	file_lore_v1_lore_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lore_v1_lore_proto_rawDesc), len(file_lore_v1_lore_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_lore_v1_lore_proto_goTypes,
		DependencyIndexes: file_lore_v1_lore_proto_depIdxs,
		EnumInfos:         file_lore_v1_lore_proto_enumTypes,
		MessageInfos:      file_lore_v1_lore_proto_msgTypes,
	}.Build()
	File_lore_v1_lore_proto = out.File
	file_lore_v1_lore_proto_goTypes = nil
	file_lore_v1_lore_proto_depIdxs = nil
}
