// Package configschema derives the JSON Schema an editor running yaml-language-server
// uses to complete and check lore.yaml. It mirrors the loader and never replaces it:
// a schema cannot see the environment or cross-reference ids.
package configschema

import (
	"encoding/json"
	"slices"
	"strconv"
	"time"

	"github.com/setthasit/Lore/internal/config"
	"github.com/setthasit/Lore/internal/envx"
	"github.com/setthasit/Lore/internal/errors/internalerror"
	"github.com/setthasit/Lore/internal/registry"
	"github.com/setthasit/Lore/sdk"
)

const draft07 = "http://json-schema.org/draft-07/schema#"

const (
	expansion       = `\$\{env:`
	durationSpan    = `([0-9]+(\.[0-9]*)?|\.[0-9]+)(ns|us|µs|μs|ms|s|m|h)`
	durationPattern = `^[-+]?(0|(` + durationSpan + `)+|[0-9]+d)$`
	urlPattern      = `^[Hh][Tt][Tt][Pp][Ss]?://[^/\s]`
)

const day = 24 * time.Hour

type node = map[string]any

type Catalog struct {
	Plugins []registry.Entry

	// Unread names declared plugins whose manifest is unknown; `use:` accepts them unchecked.
	Unread []string
}

func Generate(c Catalog) ([]byte, error) {
	body, err := json.MarshalIndent(c.document(), "", "  ")
	if err != nil {
		return nil, internalerror.NewInternalError("cannot encode the lore.yaml schema", err)
	}
	return append(body, '\n'), nil
}

func (c Catalog) document() node {
	return node{
		"$schema":              draft07,
		"description":          "Lore workspace configuration. Generated by `lore schema`; rerun it after installing or removing a plugin.",
		"type":                 "object",
		"additionalProperties": false,
		"required":             []string{"workspace", "embedder"},
		"if":                   node{"properties": node{"repos": node{"maxItems": 0}}},
		"then":                 node{"required": []string{"sources"}},
		"properties": node{
			"workspace":  described(text(), "Workspace name. The index defaults to ~/.lore/<workspace>.db."),
			"index_path": described(text(), "SQLite index file. Derived data: safe to delete, rebuilt by the next `lore sync`."),
			"plugins":    described(list(pluginDecl()), "External plugins, installed by `lore plugin install`."),
			"sources":    described(list(c.instance(lore.KindSource)), "Instances to ingest, in sync order."),
			"providers":  described(list(c.instance(lore.KindProvider)), "Model provider instances that embedder: and llm: name by id."),
			"embedder":   c.roleBinding(lore.CapabilityEmbed, "The provider and model that embed every chunk. Changing the plugin, model or dimensions needs `lore sync --reembed`."),
			"llm":        c.roleBinding(lore.CapabilityComplete, "The provider and model that synthesize prose answers for the CLI and gRPC."),
			"repos":      described(list(c.repo()), "Local clones, for blame and file history only. Zero repos is a valid ask-only workspace."),
			"query":      query(),
			"scheduler":  scheduler(),
			"server":     server(),
		},
	}
}

func pluginDecl() node {
	return closed(node{
		"name":   described(text(), "The name every use: resolves by."),
		"from":   described(text(), "A local path (./bin/lore-<name>), github.com/owner/repo@vX.Y.Z, or an https:// artifact URL."),
		"pubkey": described(text(), "Cosign or minisign public key the release checksums, or a URL artifact, must be signed with; a relative path resolves beside lore.yaml."),
	}, "name", "from")
}

func (c Catalog) instance(kind lore.Kind) node {
	plugins := c.ofKind(kind)
	block := closed(node{
		"id":   described(text(), "Defaults to the plugin name; required when one plugin is used twice; "+registry.InstanceIDRule+"."),
		"use":  c.pluginName(plugins, "The plugin this instance runs."),
		"with": described(node{}, "The settings the plugin's manifest declares; empty or absent when it needs none."),
	}, "use")

	rules := make([]node, 0, len(plugins))
	for _, e := range plugins {
		with, required := withBlock(e)
		then := node{"properties": node{"with": with}}
		if required {
			then["required"] = []string{"with"}
		}
		rules = append(rules, when("use", e.Manifest.Name, then))
	}
	if len(rules) > 0 {
		block["allOf"] = rules
	}
	return block
}

func withBlock(e registry.Entry) (block node, required bool) {
	properties := node{}
	var keys []string
	for _, f := range e.Manifest.Fields {
		properties[f.Name] = field(f)
		if f.Required {
			keys = append(keys, f.Name)
		}
	}
	secrets, secretKeys := secretProperties(e)
	for key, schema := range secrets {
		properties[key] = schema
	}
	keys = append(keys, secretKeys...)

	// No type: an empty with: decodes as null, which the loader accepts.
	block = exactKeys(properties, keys...)
	return described(block, e.Manifest.Summary), len(keys) > 0
}

func secretProperties(e registry.Entry) (properties node, required []string) {
	properties = node{}
	for _, s := range e.Manifest.Secrets {
		properties[s.Key] = secret(s, e.Origin)
		if !s.Optional && !registry.FallsBack(s, e.Origin) {
			required = append(required, s.Key)
		}
	}
	return properties, required
}

func field(f lore.Field) node {
	var schema node
	switch f.Type {
	case lore.FieldString:
		schema = text()
	case lore.FieldURL:
		schema = node{"type": "string", "pattern": urlPattern + "|" + expansion}
	case lore.FieldInt:
		schema = node{"type": "integer"}
	case lore.FieldBool:
		schema = node{"type": "boolean"}
	case lore.FieldStringList:
		schema = list(text())
		if f.Required {
			schema["minItems"] = 1
		}
	case lore.FieldDuration:
		schema = node{"type": "string", "pattern": durationPattern + "|" + expansion}
	default:
		schema = node{}
	}

	doc := f.Doc
	if f.Default != "" {
		doc = sentence(doc, "Default: "+f.Default+".")
	}
	return described(schema, doc)
}

func secret(s lore.Secret, origin string) node {
	doc := sentence(s.Doc, "Secret: the credential itself, or "+envx.Form+" to keep it out of this file.")
	if registry.FallsBack(s, origin) {
		doc = sentence(doc, "Absent, it is read from "+s.DefaultEnv+".")
	}
	return described(node{"type": "string", "minLength": 1}, doc)
}

// Each branch closes the mapping over its own keys, since additionalProperties sees only its sibling properties.
func (c Catalog) roleBinding(capability lore.Capability, doc string) node {
	direct := c.directProviders(capability)
	chain := closed(bindingKeys(c.providerName(direct), ""))
	for _, e := range slices.Backward(direct) {
		properties := bindingKeys(node{"const": e.Manifest.Name}, e.Manifest.DefaultModels[capability])
		secrets, required := secretProperties(e)
		for key, schema := range secrets {
			properties[key] = schema
		}
		branch := when("provider", e.Manifest.Name, closed(properties, required...))
		branch["else"] = chain
		chain = branch
	}

	return node{
		"type":        "object",
		"description": doc,
		"required":    []string{"provider"},
		"properties":  bindingKeys(c.providerName(direct), ""),
		"allOf":       []node{chain},
	}
}

func bindingKeys(provider node, model string) node {
	modelSchema := described(text(), "Model name, as the provider spells it.")
	if model != "" {
		modelSchema["default"] = model
	}
	return node{
		"provider":   described(provider, "A providers[] id, or a provider plugin used with its defaults; a binding naming a plugin may carry that plugin's secrets."),
		"model":      modelSchema,
		"dimensions": described(node{"type": "integer", "minimum": 0}, "Vector width, for a model that does not imply one."),
	}
}

// A plugin with a required field cannot be named directly: its settings need a providers[] entry.
func (c Catalog) directProviders(capability lore.Capability) []registry.Entry {
	var direct []registry.Entry
	for _, e := range c.ofKind(lore.KindProvider) {
		if e.Manifest.Capabilities.Declares(capability) && !slices.ContainsFunc(e.Manifest.Fields, isRequired) {
			direct = append(direct, e)
		}
	}
	return direct
}

func isRequired(f lore.Field) bool {
	return f.Required
}

// providers[] ids are the user's own words, so the plugin names are suggestions, not a closed set.
func (c Catalog) providerName(direct []registry.Entry) node {
	names := slices.Concat(names(direct), c.Unread)
	if len(names) == 0 {
		return text()
	}
	return node{"type": "string", "anyOf": []node{{"enum": names}, text()}}
}

func (c Catalog) repo() node {
	use := c.pluginName(c.ofKind(lore.KindCode), "The code plugin that reads the clone.")
	use["default"] = config.DefaultRepoPlugin
	return closed(node{
		"path":   described(text(), "A local git clone; ~ expands to your home directory."),
		"use":    use,
		"remote": described(text(), "Maps the clone onto an ingested repository, named after the forge: github:acme/myproject."),
	}, "path")
}

func (c Catalog) pluginName(plugins []registry.Entry, doc string) node {
	names := slices.Concat(names(plugins), c.Unread)
	if len(names) == 0 {
		return described(node{"type": "string", "pattern": expansion}, doc)
	}
	return described(node{"type": "string", "anyOf": []node{{"enum": names}, {"pattern": expansion}}}, doc)
}

func query() node {
	return described(closed(node{
		"event_window": described(durationSchema(), "± window for event resolution. Default: "+durationText(config.DefaultEventWindow)+"."),
		"walk_depth":   described(count(), "Default: "+strconv.Itoa(config.DefaultWalkDepth)+"."),
		"top_k":        described(count(), "Default: "+strconv.Itoa(config.DefaultTopK)+"."),
	}), "Retrieval tuning. Zero or absent keeps the default.")
}

func scheduler() node {
	return closed(node{
		"interval": described(durationSchema(), "Time between scheduled sync rounds. Default: "+durationText(config.DefaultSchedulerInterval)+"."),
	})
}

func server() node {
	return described(closed(node{
		"http_addr": described(text(), "MCP Streamable HTTP listen address. A non-loopback address needs server.mtls.cert and key."),
		"grpc_addr": described(text(), "gRPC listen address. A non-loopback address needs server.mtls.cert and key."),
		"mtls": closed(node{
			"cert":      described(text(), "Server certificate file."),
			"key":       described(text(), "Server private key file."),
			"client_ca": described(text(), "CA bundle that client certificates must chain to; setting it requires client certificates."),
		}),
	}), "Listeners for `lore serve`.")
}

func durationSchema() node {
	return node{"type": "string", "pattern": durationPattern}
}

func durationText(d config.Duration) string {
	if length := time.Duration(d); length%day == 0 {
		return strconv.Itoa(int(length/day)) + "d"
	}
	return d.String()
}

func (c Catalog) ofKind(kind lore.Kind) []registry.Entry {
	var out []registry.Entry
	for _, e := range c.Plugins {
		if e.Manifest.Kind == kind {
			out = append(out, e)
		}
	}
	return out
}

func names(entries []registry.Entry) []string {
	out := make([]string, len(entries))
	for i, e := range entries {
		out[i] = e.Manifest.Name
	}
	return out
}

func when(key, value string, then node) node {
	return node{
		"if":   node{"required": []string{key}, "properties": node{key: node{"const": value}}},
		"then": then,
	}
}

func closed(properties node, required ...string) node {
	schema := exactKeys(properties, required...)
	schema["type"] = "object"
	return schema
}

func exactKeys(properties node, required ...string) node {
	schema := node{"additionalProperties": false, "properties": properties}
	if len(required) > 0 {
		schema["required"] = required
	}
	return schema
}

func described(schema node, doc string) node {
	if doc != "" {
		schema["description"] = doc
	}
	return schema
}

func list(items node) node {
	return node{"type": "array", "items": items}
}

func text() node {
	return node{"type": "string"}
}

func count() node {
	return node{"type": "integer", "minimum": 0}
}

func sentence(first, second string) string {
	if first == "" {
		return second
	}
	return first + " " + second
}
