// Code generated by MockGen. DO NOT EDIT.
// Source: lore/internal/repositories (interfaces: IndexStore)
//
// Generated by this command:
//
//	mockgen -destination repositories/indexstore.go -package mock_repositories lore/internal/repositories IndexStore
//

// Package mock_repositories is a generated GoMock package.
package mock_repositories

import (
	context "context"
	entities "lore/internal/entities"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIndexStore is a mock of IndexStore interface.
type MockIndexStore struct {
	ctrl     *gomock.Controller
	recorder *MockIndexStoreMockRecorder
	isgomock struct{}
}

// MockIndexStoreMockRecorder is the mock recorder for MockIndexStore.
type MockIndexStoreMockRecorder struct {
	mock *MockIndexStore
}

// NewMockIndexStore creates a new mock instance.
func NewMockIndexStore(ctrl *gomock.Controller) *MockIndexStore {
	mock := &MockIndexStore{ctrl: ctrl}
	mock.recorder = &MockIndexStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIndexStore) EXPECT() *MockIndexStoreMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockIndexStore) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockIndexStoreMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockIndexStore)(nil).Close))
}

// Cursor mocks base method.
func (m *MockIndexStore) Cursor(ctx context.Context, connector string) (entities.Cursor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cursor", ctx, connector)
	ret0, _ := ret[0].(entities.Cursor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Cursor indicates an expected call of Cursor.
func (mr *MockIndexStoreMockRecorder) Cursor(ctx, connector any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cursor", reflect.TypeOf((*MockIndexStore)(nil).Cursor), ctx, connector)
}

// DeletePendingRefs mocks base method.
func (m *MockIndexStore) DeletePendingRefs(ctx context.Context, refs []entities.PendingRef) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePendingRefs", ctx, refs)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePendingRefs indicates an expected call of DeletePendingRefs.
func (mr *MockIndexStoreMockRecorder) DeletePendingRefs(ctx, refs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePendingRefs", reflect.TypeOf((*MockIndexStore)(nil).DeletePendingRefs), ctx, refs)
}

// DocumentsByID mocks base method.
func (m *MockIndexStore) DocumentsByID(ctx context.Context, ids []entities.DocID) ([]entities.DocumentMeta, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DocumentsByID", ctx, ids)
	ret0, _ := ret[0].([]entities.DocumentMeta)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DocumentsByID indicates an expected call of DocumentsByID.
func (mr *MockIndexStoreMockRecorder) DocumentsByID(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DocumentsByID", reflect.TypeOf((*MockIndexStore)(nil).DocumentsByID), ctx, ids)
}

// DocumentsWithBody mocks base method.
func (m *MockIndexStore) DocumentsWithBody(ctx context.Context, ids []entities.DocID) ([]entities.Document, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DocumentsWithBody", ctx, ids)
	ret0, _ := ret[0].([]entities.Document)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DocumentsWithBody indicates an expected call of DocumentsWithBody.
func (mr *MockIndexStoreMockRecorder) DocumentsWithBody(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DocumentsWithBody", reflect.TypeOf((*MockIndexStore)(nil).DocumentsWithBody), ctx, ids)
}

// HeartbeatLease mocks base method.
func (m *MockIndexStore) HeartbeatLease(ctx context.Context, holder string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HeartbeatLease", ctx, holder)
	ret0, _ := ret[0].(error)
	return ret0
}

// HeartbeatLease indicates an expected call of HeartbeatLease.
func (mr *MockIndexStoreMockRecorder) HeartbeatLease(ctx, holder any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HeartbeatLease", reflect.TypeOf((*MockIndexStore)(nil).HeartbeatLease), ctx, holder)
}

// Lease mocks base method.
func (m *MockIndexStore) Lease(ctx context.Context) (*entities.LeaseState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Lease", ctx)
	ret0, _ := ret[0].(*entities.LeaseState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Lease indicates an expected call of Lease.
func (mr *MockIndexStoreMockRecorder) Lease(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Lease", reflect.TypeOf((*MockIndexStore)(nil).Lease), ctx)
}

// Meta mocks base method.
func (m *MockIndexStore) Meta(ctx context.Context, key string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Meta", ctx, key)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Meta indicates an expected call of Meta.
func (mr *MockIndexStoreMockRecorder) Meta(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Meta", reflect.TypeOf((*MockIndexStore)(nil).Meta), ctx, key)
}

// Neighbors mocks base method.
func (m *MockIndexStore) Neighbors(ctx context.Context, ids []entities.DocID, kinds []entities.EdgeKind, dir entities.Direction) ([]entities.Edge, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Neighbors", ctx, ids, kinds, dir)
	ret0, _ := ret[0].([]entities.Edge)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Neighbors indicates an expected call of Neighbors.
func (mr *MockIndexStoreMockRecorder) Neighbors(ctx, ids, kinds, dir any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Neighbors", reflect.TypeOf((*MockIndexStore)(nil).Neighbors), ctx, ids, kinds, dir)
}

// PendingRefs mocks base method.
func (m *MockIndexStore) PendingRefs(ctx context.Context) ([]entities.PendingRef, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PendingRefs", ctx)
	ret0, _ := ret[0].([]entities.PendingRef)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PendingRefs indicates an expected call of PendingRefs.
func (mr *MockIndexStoreMockRecorder) PendingRefs(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PendingRefs", reflect.TypeOf((*MockIndexStore)(nil).PendingRefs), ctx)
}

// ReleaseLease mocks base method.
func (m *MockIndexStore) ReleaseLease(ctx context.Context, holder string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReleaseLease", ctx, holder)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReleaseLease indicates an expected call of ReleaseLease.
func (mr *MockIndexStoreMockRecorder) ReleaseLease(ctx, holder any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReleaseLease", reflect.TypeOf((*MockIndexStore)(nil).ReleaseLease), ctx, holder)
}

// ReplaceChunks mocks base method.
func (m *MockIndexStore) ReplaceChunks(ctx context.Context, docID entities.DocID, chunks []entities.Chunk) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplaceChunks", ctx, docID, chunks)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReplaceChunks indicates an expected call of ReplaceChunks.
func (mr *MockIndexStoreMockRecorder) ReplaceChunks(ctx, docID, chunks any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceChunks", reflect.TypeOf((*MockIndexStore)(nil).ReplaceChunks), ctx, docID, chunks)
}

// ResolveRef mocks base method.
func (m *MockIndexStore) ResolveRef(ctx context.Context, ref string) ([]entities.DocumentMeta, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveRef", ctx, ref)
	ret0, _ := ret[0].([]entities.DocumentMeta)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveRef indicates an expected call of ResolveRef.
func (mr *MockIndexStoreMockRecorder) ResolveRef(ctx, ref any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveRef", reflect.TypeOf((*MockIndexStore)(nil).ResolveRef), ctx, ref)
}

// SearchLexical mocks base method.
func (m *MockIndexStore) SearchLexical(ctx context.Context, query string, f entities.Filters, k int) ([]entities.ChunkHit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchLexical", ctx, query, f, k)
	ret0, _ := ret[0].([]entities.ChunkHit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchLexical indicates an expected call of SearchLexical.
func (mr *MockIndexStoreMockRecorder) SearchLexical(ctx, query, f, k any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchLexical", reflect.TypeOf((*MockIndexStore)(nil).SearchLexical), ctx, query, f, k)
}

// SearchVector mocks base method.
func (m *MockIndexStore) SearchVector(ctx context.Context, embedding []float32, f entities.Filters, k int) ([]entities.ChunkHit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchVector", ctx, embedding, f, k)
	ret0, _ := ret[0].([]entities.ChunkHit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchVector indicates an expected call of SearchVector.
func (mr *MockIndexStoreMockRecorder) SearchVector(ctx, embedding, f, k any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchVector", reflect.TypeOf((*MockIndexStore)(nil).SearchVector), ctx, embedding, f, k)
}

// SetCursor mocks base method.
func (m *MockIndexStore) SetCursor(ctx context.Context, connector string, c entities.Cursor) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetCursor", ctx, connector, c)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetCursor indicates an expected call of SetCursor.
func (mr *MockIndexStoreMockRecorder) SetCursor(ctx, connector, c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCursor", reflect.TypeOf((*MockIndexStore)(nil).SetCursor), ctx, connector, c)
}

// SetMeta mocks base method.
func (m *MockIndexStore) SetMeta(ctx context.Context, key, value string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetMeta", ctx, key, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetMeta indicates an expected call of SetMeta.
func (mr *MockIndexStoreMockRecorder) SetMeta(ctx, key, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMeta", reflect.TypeOf((*MockIndexStore)(nil).SetMeta), ctx, key, value)
}

// Stats mocks base method.
func (m *MockIndexStore) Stats(ctx context.Context) (entities.IndexStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stats", ctx)
	ret0, _ := ret[0].(entities.IndexStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Stats indicates an expected call of Stats.
func (mr *MockIndexStoreMockRecorder) Stats(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stats", reflect.TypeOf((*MockIndexStore)(nil).Stats), ctx)
}

// TryAcquireLease mocks base method.
func (m *MockIndexStore) TryAcquireLease(ctx context.Context, holder string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TryAcquireLease", ctx, holder)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TryAcquireLease indicates an expected call of TryAcquireLease.
func (mr *MockIndexStoreMockRecorder) TryAcquireLease(ctx, holder any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TryAcquireLease", reflect.TypeOf((*MockIndexStore)(nil).TryAcquireLease), ctx, holder)
}

// UpsertDocuments mocks base method.
func (m *MockIndexStore) UpsertDocuments(ctx context.Context, docs []entities.Document) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertDocuments", ctx, docs)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertDocuments indicates an expected call of UpsertDocuments.
func (mr *MockIndexStoreMockRecorder) UpsertDocuments(ctx, docs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertDocuments", reflect.TypeOf((*MockIndexStore)(nil).UpsertDocuments), ctx, docs)
}

// UpsertEdges mocks base method.
func (m *MockIndexStore) UpsertEdges(ctx context.Context, edges []entities.Edge) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertEdges", ctx, edges)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertEdges indicates an expected call of UpsertEdges.
func (mr *MockIndexStoreMockRecorder) UpsertEdges(ctx, edges any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertEdges", reflect.TypeOf((*MockIndexStore)(nil).UpsertEdges), ctx, edges)
}

// UpsertPendingRefs mocks base method.
func (m *MockIndexStore) UpsertPendingRefs(ctx context.Context, refs []entities.PendingRef) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertPendingRefs", ctx, refs)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertPendingRefs indicates an expected call of UpsertPendingRefs.
func (mr *MockIndexStoreMockRecorder) UpsertPendingRefs(ctx, refs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertPendingRefs", reflect.TypeOf((*MockIndexStore)(nil).UpsertPendingRefs), ctx, refs)
}

// WipeChunks mocks base method.
func (m *MockIndexStore) WipeChunks(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WipeChunks", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// WipeChunks indicates an expected call of WipeChunks.
func (mr *MockIndexStoreMockRecorder) WipeChunks(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WipeChunks", reflect.TypeOf((*MockIndexStore)(nil).WipeChunks), ctx)
}
