// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/setthasit/Lore/internal/services (interfaces: Chunker)
//
// Generated by this command:
//
//	mockgen -destination services/chunker.go -package mock_services github.com/setthasit/Lore/internal/services Chunker
//

// Package mock_services is a generated GoMock package.
package mock_services

import (
	reflect "reflect"

	entities "github.com/setthasit/Lore/internal/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockChunker is a mock of Chunker interface.
type MockChunker struct {
	ctrl     *gomock.Controller
	recorder *MockChunkerMockRecorder
	isgomock struct{}
}

// MockChunkerMockRecorder is the mock recorder for MockChunker.
type MockChunkerMockRecorder struct {
	mock *MockChunker
}

// NewMockChunker creates a new mock instance.
func NewMockChunker(ctrl *gomock.Controller) *MockChunker {
	mock := &MockChunker{ctrl: ctrl}
	mock.recorder = &MockChunkerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChunker) EXPECT() *MockChunkerMockRecorder {
	return m.recorder
}

// Chunk mocks base method.
func (m *MockChunker) Chunk(doc entities.Document) []entities.Chunk {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Chunk", doc)
	ret0, _ := ret[0].([]entities.Chunk)
	return ret0
}

// Chunk indicates an expected call of Chunk.
func (mr *MockChunkerMockRecorder) Chunk(doc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Chunk", reflect.TypeOf((*MockChunker)(nil).Chunk), doc)
}
