// Code generated by MockGen. DO NOT EDIT.
// Source: lore/internal/services (interfaces: HistoryService)
//
// Generated by this command:
//
//	mockgen -destination services/history.go -package mock_services lore/internal/services HistoryService
//

// Package mock_services is a generated GoMock package.
package mock_services

import (
	context "context"
	entities "lore/internal/entities"
	services "lore/internal/services"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockHistoryService is a mock of HistoryService interface.
type MockHistoryService struct {
	ctrl     *gomock.Controller
	recorder *MockHistoryServiceMockRecorder
	isgomock struct{}
}

// MockHistoryServiceMockRecorder is the mock recorder for MockHistoryService.
type MockHistoryServiceMockRecorder struct {
	mock *MockHistoryService
}

// NewMockHistoryService creates a new mock instance.
func NewMockHistoryService(ctrl *gomock.Controller) *MockHistoryService {
	mock := &MockHistoryService{ctrl: ctrl}
	mock.recorder = &MockHistoryServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHistoryService) EXPECT() *MockHistoryServiceMockRecorder {
	return m.recorder
}

// HistoryOf mocks base method.
func (m *MockHistoryService) HistoryOf(ctx context.Context, req services.HistoryRequest) (*entities.EvidenceBundle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HistoryOf", ctx, req)
	ret0, _ := ret[0].(*entities.EvidenceBundle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HistoryOf indicates an expected call of HistoryOf.
func (mr *MockHistoryServiceMockRecorder) HistoryOf(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HistoryOf", reflect.TypeOf((*MockHistoryService)(nil).HistoryOf), ctx, req)
}
