// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/setthasit/Lore/internal/services (interfaces: ImpactService)
//
// Generated by this command:
//
//	mockgen -destination services/impact.go -package mock_services github.com/setthasit/Lore/internal/services ImpactService
//

// Package mock_services is a generated GoMock package.
package mock_services

import (
	context "context"
	reflect "reflect"

	entities "github.com/setthasit/Lore/internal/entities"
	services "github.com/setthasit/Lore/internal/services"
	gomock "go.uber.org/mock/gomock"
)

// MockImpactService is a mock of ImpactService interface.
type MockImpactService struct {
	ctrl     *gomock.Controller
	recorder *MockImpactServiceMockRecorder
	isgomock struct{}
}

// MockImpactServiceMockRecorder is the mock recorder for MockImpactService.
type MockImpactServiceMockRecorder struct {
	mock *MockImpactService
}

// NewMockImpactService creates a new mock instance.
func NewMockImpactService(ctrl *gomock.Controller) *MockImpactService {
	mock := &MockImpactService{ctrl: ctrl}
	mock.recorder = &MockImpactServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockImpactService) EXPECT() *MockImpactServiceMockRecorder {
	return m.recorder
}

// ImpactOf mocks base method.
func (m *MockImpactService) ImpactOf(ctx context.Context, req services.ImpactRequest) (*entities.EvidenceBundle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ImpactOf", ctx, req)
	ret0, _ := ret[0].(*entities.EvidenceBundle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ImpactOf indicates an expected call of ImpactOf.
func (mr *MockImpactServiceMockRecorder) ImpactOf(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ImpactOf", reflect.TypeOf((*MockImpactService)(nil).ImpactOf), ctx, req)
}
