// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/setthasit/Lore/internal/services (interfaces: LinkResolver)
//
// Generated by this command:
//
//	mockgen -destination services/linkresolver.go -package mock_services github.com/setthasit/Lore/internal/services LinkResolver
//

// Package mock_services is a generated GoMock package.
package mock_services

import (
	context "context"
	reflect "reflect"

	entities "github.com/setthasit/Lore/internal/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockLinkResolver is a mock of LinkResolver interface.
type MockLinkResolver struct {
	ctrl     *gomock.Controller
	recorder *MockLinkResolverMockRecorder
	isgomock struct{}
}

// MockLinkResolverMockRecorder is the mock recorder for MockLinkResolver.
type MockLinkResolverMockRecorder struct {
	mock *MockLinkResolver
}

// NewMockLinkResolver creates a new mock instance.
func NewMockLinkResolver(ctrl *gomock.Controller) *MockLinkResolver {
	mock := &MockLinkResolver{ctrl: ctrl}
	mock.recorder = &MockLinkResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLinkResolver) EXPECT() *MockLinkResolverMockRecorder {
	return m.recorder
}

// Link mocks base method.
func (m *MockLinkResolver) Link(ctx context.Context, docs []entities.Document) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Link", ctx, docs)
	ret0, _ := ret[0].(error)
	return ret0
}

// Link indicates an expected call of Link.
func (mr *MockLinkResolverMockRecorder) Link(ctx, docs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Link", reflect.TypeOf((*MockLinkResolver)(nil).Link), ctx, docs)
}

// LinkPending mocks base method.
func (m *MockLinkResolver) LinkPending(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LinkPending", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// LinkPending indicates an expected call of LinkPending.
func (mr *MockLinkResolverMockRecorder) LinkPending(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LinkPending", reflect.TypeOf((*MockLinkResolver)(nil).LinkPending), ctx)
}
