// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/setthasit/Lore/internal/services (interfaces: QueryService)
//
// Generated by this command:
//
//	mockgen -destination services/query.go -package mock_services github.com/setthasit/Lore/internal/services QueryService
//

// Package mock_services is a generated GoMock package.
package mock_services

import (
	context "context"
	reflect "reflect"

	entities "github.com/setthasit/Lore/internal/entities"
	services "github.com/setthasit/Lore/internal/services"
	gomock "go.uber.org/mock/gomock"
)

// MockQueryService is a mock of QueryService interface.
type MockQueryService struct {
	ctrl     *gomock.Controller
	recorder *MockQueryServiceMockRecorder
	isgomock struct{}
}

// MockQueryServiceMockRecorder is the mock recorder for MockQueryService.
type MockQueryServiceMockRecorder struct {
	mock *MockQueryService
}

// NewMockQueryService creates a new mock instance.
func NewMockQueryService(ctrl *gomock.Controller) *MockQueryService {
	mock := &MockQueryService{ctrl: ctrl}
	mock.recorder = &MockQueryServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueryService) EXPECT() *MockQueryServiceMockRecorder {
	return m.recorder
}

// FindDecision mocks base method.
func (m *MockQueryService) FindDecision(ctx context.Context, req services.FindDecisionRequest) (*entities.EvidenceBundle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindDecision", ctx, req)
	ret0, _ := ret[0].(*entities.EvidenceBundle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindDecision indicates an expected call of FindDecision.
func (mr *MockQueryServiceMockRecorder) FindDecision(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindDecision", reflect.TypeOf((*MockQueryService)(nil).FindDecision), ctx, req)
}
