// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/setthasit/Lore/internal/services (interfaces: SyncOrchestrator)
//
// Generated by this command:
//
//	mockgen -destination services/sync.go -package mock_services github.com/setthasit/Lore/internal/services SyncOrchestrator
//

// Package mock_services is a generated GoMock package.
package mock_services

import (
	context "context"
	reflect "reflect"

	entities "github.com/setthasit/Lore/internal/entities"
	services "github.com/setthasit/Lore/internal/services"
	gomock "go.uber.org/mock/gomock"
)

// MockSyncOrchestrator is a mock of SyncOrchestrator interface.
type MockSyncOrchestrator struct {
	ctrl     *gomock.Controller
	recorder *MockSyncOrchestratorMockRecorder
	isgomock struct{}
}

// MockSyncOrchestratorMockRecorder is the mock recorder for MockSyncOrchestrator.
type MockSyncOrchestratorMockRecorder struct {
	mock *MockSyncOrchestrator
}

// NewMockSyncOrchestrator creates a new mock instance.
func NewMockSyncOrchestrator(ctrl *gomock.Controller) *MockSyncOrchestrator {
	mock := &MockSyncOrchestrator{ctrl: ctrl}
	mock.recorder = &MockSyncOrchestratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSyncOrchestrator) EXPECT() *MockSyncOrchestratorMockRecorder {
	return m.recorder
}

// Subscribe mocks base method.
func (m *MockSyncOrchestrator) Subscribe() (<-chan entities.SyncEvent, func()) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subscribe")
	ret0, _ := ret[0].(<-chan entities.SyncEvent)
	ret1, _ := ret[1].(func())
	return ret0, ret1
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockSyncOrchestratorMockRecorder) Subscribe() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockSyncOrchestrator)(nil).Subscribe))
}

// Sync mocks base method.
func (m *MockSyncOrchestrator) Sync(ctx context.Context, opts services.SyncOptions) (services.SyncResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sync", ctx, opts)
	ret0, _ := ret[0].(services.SyncResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Sync indicates an expected call of Sync.
func (mr *MockSyncOrchestratorMockRecorder) Sync(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sync", reflect.TypeOf((*MockSyncOrchestrator)(nil).Sync), ctx, opts)
}
