// Code generated by MockGen. DO NOT EDIT.
// Source: lore/internal/services (interfaces: SynthesisService)
//
// Generated by this command:
//
//	mockgen -destination services/synthesis.go -package mock_services lore/internal/services SynthesisService
//

// Package mock_services is a generated GoMock package.
package mock_services

import (
	context "context"
	entities "lore/internal/entities"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSynthesisService is a mock of SynthesisService interface.
type MockSynthesisService struct {
	ctrl     *gomock.Controller
	recorder *MockSynthesisServiceMockRecorder
	isgomock struct{}
}

// MockSynthesisServiceMockRecorder is the mock recorder for MockSynthesisService.
type MockSynthesisServiceMockRecorder struct {
	mock *MockSynthesisService
}

// NewMockSynthesisService creates a new mock instance.
func NewMockSynthesisService(ctrl *gomock.Controller) *MockSynthesisService {
	mock := &MockSynthesisService{ctrl: ctrl}
	mock.recorder = &MockSynthesisServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSynthesisService) EXPECT() *MockSynthesisServiceMockRecorder {
	return m.recorder
}

// Synthesize mocks base method.
func (m *MockSynthesisService) Synthesize(ctx context.Context, question string, bundle *entities.EvidenceBundle) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Synthesize", ctx, question, bundle)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Synthesize indicates an expected call of Synthesize.
func (mr *MockSynthesisServiceMockRecorder) Synthesize(ctx, question, bundle any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Synthesize", reflect.TypeOf((*MockSynthesisService)(nil).Synthesize), ctx, question, bundle)
}
