// Code generated by MockGen. DO NOT EDIT.
// Source: lore/internal/services (interfaces: TraceService)
//
// Generated by this command:
//
//	mockgen -destination services/trace.go -package mock_services lore/internal/services TraceService
//

// Package mock_services is a generated GoMock package.
package mock_services

import (
	context "context"
	entities "lore/internal/entities"
	services "lore/internal/services"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTraceService is a mock of TraceService interface.
type MockTraceService struct {
	ctrl     *gomock.Controller
	recorder *MockTraceServiceMockRecorder
	isgomock struct{}
}

// MockTraceServiceMockRecorder is the mock recorder for MockTraceService.
type MockTraceServiceMockRecorder struct {
	mock *MockTraceService
}

// NewMockTraceService creates a new mock instance.
func NewMockTraceService(ctrl *gomock.Controller) *MockTraceService {
	mock := &MockTraceService{ctrl: ctrl}
	mock.recorder = &MockTraceServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTraceService) EXPECT() *MockTraceServiceMockRecorder {
	return m.recorder
}

// Trace mocks base method.
func (m *MockTraceService) Trace(ctx context.Context, req services.TraceRequest) (*entities.EvidenceBundle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Trace", ctx, req)
	ret0, _ := ret[0].(*entities.EvidenceBundle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Trace indicates an expected call of Trace.
func (mr *MockTraceServiceMockRecorder) Trace(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Trace", reflect.TypeOf((*MockTraceService)(nil).Trace), ctx, req)
}
