// Code generated by MockGen. DO NOT EDIT.
// Source: lore/internal/services (interfaces: WhyService)
//
// Generated by this command:
//
//	mockgen -destination services/why.go -package mock_services lore/internal/services WhyService
//

// Package mock_services is a generated GoMock package.
package mock_services

import (
	context "context"
	entities "lore/internal/entities"
	services "lore/internal/services"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockWhyService is a mock of WhyService interface.
type MockWhyService struct {
	ctrl     *gomock.Controller
	recorder *MockWhyServiceMockRecorder
	isgomock struct{}
}

// MockWhyServiceMockRecorder is the mock recorder for MockWhyService.
type MockWhyServiceMockRecorder struct {
	mock *MockWhyService
}

// NewMockWhyService creates a new mock instance.
func NewMockWhyService(ctrl *gomock.Controller) *MockWhyService {
	mock := &MockWhyService{ctrl: ctrl}
	mock.recorder = &MockWhyServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWhyService) EXPECT() *MockWhyServiceMockRecorder {
	return m.recorder
}

// Why mocks base method.
func (m *MockWhyService) Why(ctx context.Context, req services.WhyRequest) (*entities.EvidenceBundle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Why", ctx, req)
	ret0, _ := ret[0].(*entities.EvidenceBundle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Why indicates an expected call of Why.
func (mr *MockWhyServiceMockRecorder) Why(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Why", reflect.TypeOf((*MockWhyService)(nil).Why), ctx, req)
}
